/**
 * Industry-Specific Tracks - Data
 * 
 * Comprehensive data for Healthcare, Manufacturing, Service, IT/Software, and Finance industries
 */

import type { IndustryTrack, IndustryModule } from './types';

export const INDUSTRY_TRACKS: Record<string, IndustryTrack> = {
  healthcare: {
    id: 'healthcare',
    name: 'Healthcare & Life Sciences',
    description: 'Apply Six Sigma to improve patient outcomes, reduce medical errors, optimize hospital operations, and enhance healthcare quality.',
    icon: '🏥',
    color: '#E91E63',
    challenges: [
      'Patient wait times',
      'Medication errors',
      'Hospital-acquired infections',
      'Readmission rates',
      'Operating room turnover',
      'Supply chain management',
      'Regulatory compliance',
    ],
    applications: [
      'Emergency department flow',
      'Surgical scheduling',
      'Pharmacy operations',
      'Laboratory turnaround',
      'Patient discharge process',
      'Medical device sterilization',
      'Clinical trial processes',
    ],
    metrics: [
      'Patient satisfaction scores',
      'Mortality rates',
      'Infection rates',
      'Length of stay',
      'Cost per case',
      'Bed utilization',
      'Staff overtime',
    ],
    caseStudies: [
      {
        id: 'h1',
        title: 'Reducing Emergency Department Wait Times',
        company: 'Metro General Hospital',
        industry: 'Healthcare',
        challenge: 'Average ER wait time was 4.5 hours, leading to patient dissatisfaction and walkouts',
        approach: 'Applied Lean Six Sigma to patient flow, triage process, and resource allocation',
        results: [
          { metric: 'Average Wait Time', before: '4.5 hours', after: '1.8 hours', improvement: '60% reduction' },
          { metric: 'Patient Satisfaction', before: '62%', after: '89%', improvement: '+27 points' },
          { metric: 'Left Without Being Seen', before: '8%', after: '2%', improvement: '75% reduction' },
        ],
        dmaicPhase: 'Improve',
        duration: '8 months',
        teamSize: 8,
        roi: '$2.4M annually',
      },
      {
        id: 'h2',
        title: 'Decreasing Hospital-Acquired Infections',
        company: 'Regional Medical Center',
        industry: 'Healthcare',
        challenge: 'CLABSI (Central Line Bloodstream Infection) rates exceeded national benchmarks',
        approach: 'DMAIC approach to hand hygiene compliance, sterile technique, and maintenance protocols',
        results: [
          { metric: 'CLABSI Rate', before: '3.2 per 1000 line-days', after: '0.8 per 1000 line-days', improvement: '75% reduction' },
          { metric: 'Hand Hygiene Compliance', before: '72%', after: '96%', improvement: '+24 points' },
          { metric: 'Cost Avoidance', before: '$0', after: '$1.8M', improvement: 'Annual savings' },
        ],
        dmaicPhase: 'Control',
        duration: '12 months',
        teamSize: 12,
        roi: '$1.8M annually',
      },
    ],
    tools: [
      {
        id: 'ht1',
        name: 'Process Mapping',
        description: 'Map patient journeys and clinical workflows',
        application: 'Identify bottlenecks in care delivery',
        difficulty: 'beginner',
        whenToUse: ['Patient flow optimization', 'Discharge planning', 'Emergency department'],
        examples: ['Value stream mapping for surgery scheduling', 'SIPOC for medication administration'],
      },
      {
        id: 'ht2',
        name: 'FMEA',
        description: 'Failure Mode and Effects Analysis',
        application: 'Risk assessment for patient safety',
        difficulty: 'intermediate',
        whenToUse: ['New procedure implementation', 'Medical device selection', 'Protocol changes'],
        examples: ['Surgical safety checklist FMEA', 'Medication administration FMEA'],
      },
      {
        id: 'ht3',
        name: 'Statistical Process Control',
        description: 'Control charts for clinical metrics',
        application: 'Monitor infection rates and outcomes',
        difficulty: 'advanced',
        whenToUse: ['Quality metrics tracking', 'Outcome monitoring', 'Benchmarking'],
        examples: ['p-chart for infection rates', 'X-bar R for lab turnaround times'],
      },
    ],
    certificationPath: [
      {
        level: 'white',
        focus: ['Healthcare quality basics', 'Patient safety fundamentals'],
        projects: ['Observe a rapid improvement event', 'Shadow a Green Belt project'],
        duration: '1 day',
        prerequisites: [],
        industrySpecificSkills: ['HIPAA awareness', 'Patient-centered care principles'],
      },
      {
        level: 'yellow',
        focus: ['Process mapping in healthcare', 'Basic data collection'],
        projects: ['Process mapping exercise', 'Data collection for quality metrics'],
        duration: '1 week',
        prerequisites: ['White Belt'],
        industrySpecificSkills: ['Clinical workflow understanding', 'Healthcare terminology'],
      },
      {
        level: 'green',
        focus: ['Clinical process improvement', 'Root cause analysis', 'Patient safety'],
        projects: ['Lead a 4-month improvement project', 'Reduce wait times or errors'],
        duration: '4-6 months',
        prerequisites: ['Yellow Belt', '2 years healthcare experience'],
        industrySpecificSkills: ['Clinical analytics', 'Regulatory compliance', 'Change management in clinical settings'],
      },
      {
        level: 'black',
        focus: ['Enterprise transformation', 'Advanced statistics', 'Strategic planning'],
        projects: ['Lead 2 major projects', 'Mentor Green Belts', 'Develop organizational strategy'],
        duration: '12-18 months',
        prerequisites: ['Green Belt', '5 years healthcare experience'],
        industrySpecificSkills: ['Population health management', 'Value-based care', 'Healthcare economics'],
      },
    ],
    statistics: {
      averageProjectDuration: '6-9 months',
      typicalTeamSize: '6-10 members',
      commonProjectTypes: ['Patient flow', 'Quality improvement', 'Cost reduction'],
      successRate: '78%',
      averageSavings: '$250K-$1M per project',
    },
  },

  manufacturing: {
    id: 'manufacturing',
    name: 'Manufacturing & Operations',
    description: 'The birthplace of Six Sigma. Optimize production lines, reduce defects, improve yield, and eliminate waste in manufacturing environments.',
    icon: '🏭',
    color: '#FF9800',
    challenges: [
      'Product defects',
      'Equipment downtime',
      'Inventory management',
      'Production bottlenecks',
      'Supplier quality',
      'Yield optimization',
      'Energy consumption',
    ],
    applications: [
      'Assembly line optimization',
      'Quality control processes',
      'Preventive maintenance',
      'Supply chain management',
      'Product design for Six Sigma',
      'Workplace safety',
      'Environmental compliance',
    ],
    metrics: [
      'First pass yield',
      'Overall Equipment Effectiveness (OEE)',
      'Defects per million opportunities (DPMO)',
      'Cycle time',
      'Scrap rate',
      'On-time delivery',
      'Cost of poor quality',
    ],
    caseStudies: [
      {
        id: 'm1',
        title: 'Improving First Pass Yield',
        company: 'Precision Components Inc.',
        industry: 'Manufacturing',
        challenge: 'First pass yield at 82%, causing rework costs and delays',
        approach: 'DMAIC with focus on critical process parameters and SPC implementation',
        results: [
          { metric: 'First Pass Yield', before: '82%', after: '97%', improvement: '+15 points' },
          { metric: 'Scrap Rate', before: '6.5%', after: '1.2%', improvement: '82% reduction' },
          { metric: 'Annual Savings', before: '$0', after: '$3.2M', improvement: 'Direct cost savings' },
        ],
        dmaicPhase: 'Improve',
        duration: '6 months',
        teamSize: 6,
        roi: '$3.2M annually',
      },
      {
        id: 'm2',
        title: 'Reducing Equipment Downtime',
        company: 'AutoParts Manufacturer',
        industry: 'Manufacturing',
        challenge: 'Unplanned downtime averaging 15% of production time',
        approach: 'TPM (Total Productive Maintenance) combined with Six Sigma tools',
        results: [
          { metric: 'Unplanned Downtime', before: '15%', after: '4%', improvement: '73% reduction' },
          { metric: 'OEE', before: '68%', after: '86%', improvement: '+18 points' },
          { metric: 'MTBF', before: '120 hours', after: '380 hours', improvement: '217% improvement' },
        ],
        dmaicPhase: 'Control',
        duration: '10 months',
        teamSize: 8,
        roi: '$4.5M annually',
      },
    ],
    tools: [
      {
        id: 'mt1',
        name: 'SPC (Statistical Process Control)',
        description: 'Control charts for manufacturing processes',
        application: 'Monitor and control process variation',
        difficulty: 'intermediate',
        whenToUse: ['Continuous processes', 'Batch operations', 'Quality monitoring'],
        examples: ['X-bar R charts for machining', 'p-charts for defect monitoring'],
      },
      {
        id: 'mt2',
        name: 'DOE (Design of Experiments)',
        description: 'Optimize process parameters',
        application: 'Find optimal machine settings',
        difficulty: 'advanced',
        whenToUse: ['Process optimization', 'New product development', 'Troubleshooting'],
        examples: ['Injection molding optimization', 'Welding parameter optimization'],
      },
      {
        id: 'mt3',
        name: '5S & Visual Management',
        description: 'Workplace organization system',
        application: 'Improve efficiency and safety',
        difficulty: 'beginner',
        whenToUse: ['Workplace organization', 'Safety improvement', 'Waste reduction'],
        examples: ['Tool organization', 'Visual work instructions'],
      },
    ],
    certificationPath: [
      {
        level: 'white',
        focus: ['Manufacturing basics', 'Quality concepts'],
        projects: ['Plant tour with process observation'],
        duration: '1 day',
        prerequisites: [],
        industrySpecificSkills: ['Safety awareness', 'Lean manufacturing basics'],
      },
      {
        level: 'yellow',
        focus: ['5S implementation', 'Basic problem solving'],
        projects: ['Participate in 5S event', 'Data collection project'],
        duration: '1 week',
        prerequisites: ['White Belt'],
        industrySpecificSkills: ['Manufacturing processes', 'Quality inspection basics'],
      },
      {
        level: 'green',
        focus: ['Process capability', 'SPC implementation', 'Kaizen events'],
        projects: ['Lead process improvement project', 'Implement SPC on production line'],
        duration: '4-6 months',
        prerequisites: ['Yellow Belt', '2 years manufacturing experience'],
        industrySpecificSkills: ['Process capability analysis', 'Equipment troubleshooting', 'Production planning'],
      },
      {
        level: 'black',
        focus: ['DFSS', 'Advanced DOE', 'Enterprise deployment'],
        projects: ['Lead complex multi-site projects', 'Develop manufacturing strategy'],
        duration: '12-18 months',
        prerequisites: ['Green Belt', '5 years manufacturing experience'],
        industrySpecificSkills: ['DFSS/DFMA', 'Advanced statistical analysis', 'Supply chain optimization'],
      },
    ],
    statistics: {
      averageProjectDuration: '4-8 months',
      typicalTeamSize: '4-8 members',
      commonProjectTypes: ['Yield improvement', 'Defect reduction', 'Cycle time reduction'],
      successRate: '85%',
      averageSavings: '$500K-$5M per project',
    },
  },

  service: {
    id: 'service',
    name: 'Service & Hospitality',
    description: 'Adapt Six Sigma for service industries to improve customer experience, reduce service times, and optimize back-office operations.',
    icon: '🏨',
    color: '#03A9F4',
    challenges: [
      'Customer wait times',
      'Service quality consistency',
      'Employee turnover',
      'Customer complaints',
      'Process standardization',
      'Seasonal demand variation',
      'Multi-location coordination',
    ],
    applications: [
      'Customer service operations',
      'Hotel check-in/check-out',
      'Restaurant service flow',
      'Call center optimization',
      'Back-office processing',
      'Reservation systems',
      'Housekeeping efficiency',
    ],
    metrics: [
      'Customer satisfaction (CSAT)',
      'Net Promoter Score (NPS)',
      'Average handling time',
      'First call resolution',
      'Service level agreement (SLA) compliance',
      'Employee satisfaction',
      'Revenue per available room (RevPAR)',
    ],
    caseStudies: [
      {
        id: 's1',
        title: 'Hotel Check-in Process Optimization',
        company: 'Grand Hotel Chain',
        industry: 'Hospitality',
        challenge: 'Average check-in time of 8 minutes causing lobby congestion',
        approach: 'Lean Six Sigma to streamline registration and key distribution',
        results: [
          { metric: 'Average Check-in Time', before: '8 minutes', after: '3.5 minutes', improvement: '56% reduction' },
          { metric: 'Guest Satisfaction', before: '3.8/5', after: '4.6/5', improvement: '+0.8 points' },
          { metric: 'Lobby Wait Time', before: '12 minutes', after: '4 minutes', improvement: '67% reduction' },
        ],
        dmaicPhase: 'Improve',
        duration: '5 months',
        teamSize: 5,
        roi: '$850K annually',
      },
      {
        id: 's2',
        title: 'Call Center First Call Resolution',
        company: 'Telecom Customer Service',
        industry: 'Service',
        challenge: 'First call resolution at 62%, leading to callbacks and dissatisfaction',
        approach: 'Root cause analysis and agent training optimization',
        results: [
          { metric: 'First Call Resolution', before: '62%', after: '84%', improvement: '+22 points' },
          { metric: 'Average Handle Time', before: '8.5 min', after: '6.2 min', improvement: '27% reduction' },
          { metric: 'Customer Complaints', before: '4.2%', after: '1.8%', improvement: '57% reduction' },
        ],
        dmaicPhase: 'Control',
        duration: '7 months',
        teamSize: 7,
        roi: '$1.2M annually',
      },
    ],
    tools: [
      {
        id: 'st1',
        name: 'Service Blueprinting',
        description: 'Map customer touchpoints and backstage processes',
        application: 'Identify service failure points',
        difficulty: 'intermediate',
        whenToUse: ['New service design', 'Service redesign', 'Journey mapping'],
        examples: ['Hotel guest journey mapping', 'Customer service blueprint'],
      },
      {
        id: 'st2',
        name: 'Customer Effort Score',
        description: 'Measure ease of customer interaction',
        application: 'Reduce friction in service processes',
        difficulty: 'beginner',
        whenToUse: ['Service optimization', 'Process simplification'],
        examples: ['Online booking process', 'Complaint resolution process'],
      },
      {
        id: 'st3',
        name: 'Voice of Customer (VOC)',
        description: 'Collect and analyze customer feedback',
        application: 'Understand customer needs and expectations',
        difficulty: 'intermediate',
        whenToUse: ['Service design', 'Quality improvement', 'Complaint analysis'],
        examples: ['Survey design', 'Focus groups', 'Social media analysis'],
      },
    ],
    certificationPath: [
      {
        level: 'white',
        focus: ['Service quality basics', 'Customer focus principles'],
        projects: ['Customer journey observation'],
        duration: '1 day',
        prerequisites: [],
        industrySpecificSkills: ['Customer service awareness', 'Empathy training'],
      },
      {
        level: 'yellow',
        focus: ['Service process mapping', 'Basic data collection'],
        projects: ['Service observation project', 'Data collection on service times'],
        duration: '1 week',
        prerequisites: ['White Belt'],
        industrySpecificSkills: ['Service delivery understanding', 'Customer interaction'],
      },
      {
        level: 'green',
        focus: ['Service process optimization', 'Customer experience improvement'],
        projects: ['Lead service improvement project', 'Reduce wait times or errors'],
        duration: '4-6 months',
        prerequisites: ['Yellow Belt', '2 years service industry experience'],
        industrySpecificSkills: ['Service quality metrics', 'Customer satisfaction analysis', 'Training delivery'],
      },
      {
        level: 'black',
        focus: ['Service innovation', 'Multi-site deployment', 'Strategy'],
        projects: ['Lead enterprise-wide service transformation', 'Develop service standards'],
        duration: '12-18 months',
        prerequisites: ['Green Belt', '5 years service industry experience'],
        industrySpecificSkills: ['Service design', 'Organizational development', 'Customer strategy'],
      },
    ],
    statistics: {
      averageProjectDuration: '5-8 months',
      typicalTeamSize: '4-6 members',
      commonProjectTypes: ['Service time reduction', 'Quality improvement', 'Cost reduction'],
      successRate: '82%',
      averageSavings: '$200K-$800K per project',
    },
  },

  'it-software': {
    id: 'it-software',
    name: 'IT & Software Development',
    description: 'Apply Six Sigma and Lean principles to software development, IT operations, and digital transformation initiatives.',
    icon: '💻',
    color: '#9C27B0',
    challenges: [
      'Software defects',
      'Project delivery delays',
      'System downtime',
      'Technical debt',
      'Resource utilization',
      'Change management',
      'Security vulnerabilities',
    ],
    applications: [
      'Software development lifecycle',
      'DevOps and CI/CD pipelines',
      'IT service management',
      'Help desk operations',
      'Infrastructure management',
      'Code quality improvement',
      'Release management',
    ],
    metrics: [
      'Defect density',
      'Mean time to repair (MTTR)',
      'Deployment frequency',
      'Lead time for changes',
      'Change failure rate',
      'System uptime',
      'Cycle time',
    ],
    caseStudies: [
      {
        id: 'i1',
        title: 'Reducing Software Defects',
        company: 'Financial Software Corp',
        industry: 'IT/Software',
        challenge: 'Production defects averaging 12 per release, causing customer dissatisfaction',
        approach: 'DMAIC applied to code review process and testing automation',
        results: [
          { metric: 'Defects per Release', before: '12', after: '3', improvement: '75% reduction' },
          { metric: 'Code Review Coverage', before: '45%', after: '95%', improvement: '+50 points' },
          { metric: 'Automated Test Coverage', before: '32%', after: '78%', improvement: '+46 points' },
        ],
        dmaicPhase: 'Control',
        duration: '9 months',
        teamSize: 6,
        roi: '$2.1M annually',
      },
      {
        id: 'i2',
        title: 'IT Help Desk Optimization',
        company: 'Enterprise IT Services',
        industry: 'IT/Software',
        challenge: 'Average resolution time of 4.2 hours and 38% first-contact resolution',
        approach: 'Knowledge base optimization and ticket categorization improvement',
        results: [
          { metric: 'First Contact Resolution', before: '38%', after: '71%', improvement: '+33 points' },
          { metric: 'Average Resolution Time', before: '4.2 hours', after: '1.8 hours', improvement: '57% reduction' },
          { metric: 'Customer Satisfaction', before: '3.2/5', after: '4.4/5', improvement: '+1.2 points' },
        ],
        dmaicPhase: 'Improve',
        duration: '6 months',
        teamSize: 5,
        roi: '$980K annually',
      },
    ],
    tools: [
      {
        id: 'it1',
        name: 'Agile Metrics & Kanban',
        description: 'Visual workflow management for development teams',
        application: 'Optimize development flow',
        difficulty: 'beginner',
        whenToUse: ['Sprint planning', 'Workflow visualization', 'Bottleneck identification'],
        examples: ['Cumulative flow diagrams', 'Cycle time analysis'],
      },
      {
        id: 'it2',
        name: 'Defect Tracking Analysis',
        description: 'Root cause analysis of software defects',
        application: 'Reduce defect injection and leakage',
        difficulty: 'intermediate',
        whenToUse: ['Release retrospective', 'Quality improvement', 'Process optimization'],
        examples: ['Pareto analysis of defects', 'Defect trend analysis'],
      },
      {
        id: 'it3',
        name: 'Value Stream Mapping',
        description: 'Map end-to-end development process',
        application: 'Identify waste in SDLC',
        difficulty: 'advanced',
        whenToUse: ['DevOps transformation', 'Process redesign', 'Lead time reduction'],
        examples: ['Feature to production mapping', 'Deployment pipeline analysis'],
      },
    ],
    certificationPath: [
      {
        level: 'white',
        focus: ['IT process basics', 'Quality in software'],
        projects: ['Shadow a development team'],
        duration: '1 day',
        prerequisites: [],
        industrySpecificSkills: ['SDLC awareness', 'Basic programming concepts'],
      },
      {
        level: 'yellow',
        focus: ['Agile fundamentals', 'Basic metrics'],
        projects: ['Sprint retrospective participation', 'Data collection'],
        duration: '1 week',
        prerequisites: ['White Belt'],
        industrySpecificSkills: ['Agile/Scrum basics', 'Issue tracking tools'],
      },
      {
        level: 'green',
        focus: ['Process improvement in IT', 'Defect reduction', 'Cycle time optimization'],
        projects: ['Lead IT improvement project', 'Optimize deployment process'],
        duration: '4-6 months',
        prerequisites: ['Yellow Belt', '2 years IT experience'],
        industrySpecificSkills: ['Software testing', 'DevOps principles', 'ITIL fundamentals'],
      },
      {
        level: 'black',
        focus: ['Enterprise IT transformation', 'DevOps at scale', 'Technical leadership'],
        projects: ['Lead IT transformation initiative', 'Mentor multiple teams'],
        duration: '12-18 months',
        prerequisites: ['Green Belt', '5 years IT experience'],
        industrySpecificSkills: ['Enterprise architecture', 'Digital transformation', 'Cloud technologies'],
      },
    ],
    statistics: {
      averageProjectDuration: '6-10 months',
      typicalTeamSize: '4-7 members',
      commonProjectTypes: ['Defect reduction', 'Cycle time improvement', 'Process automation'],
      successRate: '80%',
      averageSavings: '$400K-$2M per project',
    },
  },

  finance: {
    id: 'finance',
    name: 'Financial Services',
    description: 'Apply Six Sigma to banking, insurance, and financial operations to reduce errors, improve compliance, and enhance customer experience.',
    icon: '🏦',
    color: '#4CAF50',
    challenges: [
      'Transaction errors',
      'Regulatory compliance',
      'Loan processing time',
      'Fraud detection',
      'Account opening delays',
      'Audit findings',
      'Customer onboarding',
    ],
    applications: [
      'Loan origination process',
      'Account opening',
      'Claims processing',
      'Trading operations',
      'Compliance monitoring',
      'Reconciliation processes',
      'Customer service',
    ],
    metrics: [
      'Error rate',
      'Processing time',
      'Cost per transaction',
      'Regulatory compliance rate',
      'Customer satisfaction',
      'Straight-through processing rate',
      'Fraud detection rate',
    ],
    caseStudies: [
      {
        id: 'f1',
        title: 'Loan Processing Time Reduction',
        company: 'Regional Bank',
        industry: 'Financial Services',
        challenge: 'Average loan processing time of 21 days, losing customers to competitors',
        approach: 'Value stream mapping and bottleneck elimination',
        results: [
          { metric: 'Processing Time', before: '21 days', after: '7 days', improvement: '67% reduction' },
          { metric: 'Application Abandonment', before: '35%', after: '12%', improvement: '66% reduction' },
          { metric: 'Customer Satisfaction', before: '3.4/5', after: '4.5/5', improvement: '+1.1 points' },
        ],
        dmaicPhase: 'Improve',
        duration: '8 months',
        teamSize: 8,
        roi: '$5.2M annually',
      },
      {
        id: 'f2',
        title: 'Reducing Reconciliation Errors',
        company: 'Investment Firm',
        industry: 'Financial Services',
        challenge: 'Daily reconciliation errors averaging 45 per day, requiring manual intervention',
        approach: 'Root cause analysis and automated validation implementation',
        results: [
          { metric: 'Daily Errors', before: '45', after: '6', improvement: '87% reduction' },
          { metric: 'Reconciliation Time', before: '4 hours', after: '45 minutes', improvement: '81% reduction' },
          { metric: 'Labor Cost', before: '$840K', after: '$180K', improvement: '$660K savings' },
        ],
        dmaicPhase: 'Control',
        duration: '7 months',
        teamSize: 6,
        roi: '$660K annually',
      },
    ],
    tools: [
      {
        id: 'ft1',
        name: 'Process Mining',
        description: 'Analyze actual process execution from event logs',
        application: 'Identify process variations and bottlenecks',
        difficulty: 'advanced',
        whenToUse: ['Process discovery', 'Compliance checking', 'Performance analysis'],
        examples: ['Loan process analysis', 'Payment processing optimization'],
      },
      {
        id: 'ft2',
        name: 'Error Proofing (Poka-Yoke)',
        description: 'Prevent errors in financial transactions',
        application: 'Reduce transaction errors',
        difficulty: 'intermediate',
        whenToUse: ['Data entry processes', 'Form design', 'System interfaces'],
        examples: ['Automatic validation rules', 'Double-entry verification'],
      },
      {
        id: 'ft3',
        name: 'Value Stream Mapping',
        description: 'Map financial processes end-to-end',
        application: 'Identify non-value-added activities',
        difficulty: 'intermediate',
        whenToUse: ['Process redesign', 'Automation opportunities', 'Cost reduction'],
        examples: ['Loan origination VSM', 'Claims processing VSM'],
      },
    ],
    certificationPath: [
      {
        level: 'white',
        focus: ['Financial process basics', 'Regulatory awareness'],
        projects: ['Process observation in banking operations'],
        duration: '1 day',
        prerequisites: [],
        industrySpecificSkills: ['Financial terminology', 'Compliance basics'],
      },
      {
        level: 'yellow',
        focus: ['Financial data analysis', 'Basic process mapping'],
        projects: ['Data collection project', 'Process mapping exercise'],
        duration: '1 week',
        prerequisites: ['White Belt'],
        industrySpecificSkills: ['Financial analysis', 'Risk awareness'],
      },
      {
        level: 'green',
        focus: ['Financial process optimization', 'Compliance improvement'],
        projects: ['Lead process improvement in financial operations', 'Reduce errors or cycle time'],
        duration: '4-6 months',
        prerequisites: ['Yellow Belt', '2 years financial services experience'],
        industrySpecificSkills: ['Financial regulations', 'Risk management', 'Compliance processes'],
      },
      {
        level: 'black',
        focus: ['Enterprise transformation', 'Strategic initiatives', 'Risk management'],
        projects: ['Lead enterprise process transformation', 'Develop compliance frameworks'],
        duration: '12-18 months',
        prerequisites: ['Green Belt', '5 years financial services experience'],
        industrySpecificSkills: ['Enterprise risk management', 'Regulatory strategy', 'Financial modeling'],
      },
    ],
    statistics: {
      averageProjectDuration: '7-10 months',
      typicalTeamSize: '5-8 members',
      commonProjectTypes: ['Error reduction', 'Cycle time reduction', 'Compliance improvement'],
      successRate: '81%',
      averageSavings: '$500K-$3M per project',
    },
  },
};

// Industry-specific learning modules
export const INDUSTRY_MODULES: IndustryModule[] = [
  {
    id: 'healthcare-basics',
    industryId: 'healthcare',
    title: 'Healthcare Quality Fundamentals',
    description: 'Learn Six Sigma applications specific to healthcare environments',
    lessons: [
      {
        id: 'h1-1',
        title: 'Patient Safety and Quality',
        content: 'Understanding the unique challenges of healthcare quality improvement...',
        examples: ['Medication error reduction', 'Fall prevention programs'],
        exercises: [
          {
            id: 'h1-1-e1',
            type: 'scenario',
            title: 'ER Wait Time Analysis',
            description: 'Analyze patient flow in an emergency department',
          },
        ],
        duration: 30,
      },
      {
        id: 'h1-2',
        title: 'Healthcare Metrics',
        content: 'Key performance indicators specific to healthcare...',
        examples: ['HCAHPS scores', 'Clinical quality measures'],
        exercises: [],
        duration: 25,
      },
    ],
    quiz: {
      id: 'h1-quiz',
      questions: [
        {
          id: 'q1',
          type: 'multiple-choice',
          question: 'Which metric is most critical for patient safety?',
          options: ['Revenue per bed', 'Medication error rate', 'Staff overtime', 'Supply costs'],
          correctAnswer: 1,
          explanation: 'Medication error rate directly impacts patient safety and is a key quality indicator.',
          industryContext: 'Healthcare',
        },
      ],
      passingScore: 80,
      timeLimit: 15,
    },
  },
  {
    id: 'manufacturing-basics',
    industryId: 'manufacturing',
    title: 'Manufacturing Excellence',
    description: 'Master Six Sigma in manufacturing and production environments',
    lessons: [
      {
        id: 'm1-1',
        title: 'Production Process Control',
        content: 'Statistical process control in manufacturing...',
        examples: ['Machine capability studies', 'Control chart implementation'],
        exercises: [
          {
            id: 'm1-1-e1',
            type: 'calculation',
            title: 'Cp and Cpk Calculation',
            description: 'Calculate process capability indices',
          },
        ],
        duration: 35,
      },
    ],
    quiz: {
      id: 'm1-quiz',
      questions: [
        {
          id: 'q1',
          type: 'multiple-choice',
          question: 'What does Cpk > 1.33 indicate?',
          options: ['Process is out of control', 'Process is capable', 'Specification is wrong', 'Measurement error'],
          correctAnswer: 1,
          explanation: 'Cpk > 1.33 indicates the process is capable with good margin.',
          industryContext: 'Manufacturing',
        },
      ],
      passingScore: 80,
      timeLimit: 15,
    },
  },
];
