/**
 * JMP Export Generator
 * 
 * Generates JMP scripts and data tables for Six Sigma analysis
 */

import type { Dataset, AnalysisResults, ExportConfig } from '../types';

export interface JMPExport {
  jslScript: string;
  dataFile: string;
  journalTemplate: string;
  filename: string;
}

/**
 * Generate JMP Scripting Language (JSL) for complete analysis
 */
export function generateJMPExport(
  dataset: Dataset,
  results: AnalysisResults,
  config: ExportConfig
): JMPExport {
  const jslScript = generateJSLScript(dataset, results, config);
  const dataFile = generateJMPDataFile(dataset);
  const journalTemplate = generateJMPJournal(dataset, results);
  
  return {
    jslScript,
    dataFile,
    journalTemplate,
    filename: `${dataset.name.replace(/\s+/g, '_')}_JMP.jsl`,
  };
}

function generateJSLScript(
  dataset: Dataset,
  results: AnalysisResults,
  _config: ExportConfig
): string {
  return `// Six Sigma Analysis - JMP Script
// Generated by Six Sigma Training Platform
// Date: ${new Date().toLocaleString()}
// Dataset: ${dataset.name}

// ============================================================
// CLEAR AND SETUP
// ============================================================

Clear Log();
Close All(Data Tables, "No Save");
Close All(Reports, "No Save");

// ============================================================
// CREATE DATA TABLE
// ============================================================

dt = New Table("${dataset.name}",
  Add Rows(${dataset.rows.length}),
${dataset.columns.map((col, idx) => {
  const values = dataset.rows.slice(0, 20).map(r => {
    const val = r[idx];
    if (val === null || val === undefined) return '.';
    if (typeof val === 'string') return `"${val}"`;
    return String(val);
  }).join(', ');
  return `  New Column("${col.name}", Numeric, "Continuous", Format("Best", 10), Set Values([${values}${dataset.rows.length > 20 ? ', ...' : ''}]))`;
}).join(',\n')}
);

// ============================================================
// COLUMN INFORMATION
// ============================================================

${dataset.columns.map(col => `
// Column: ${col.name}
// Type: ${col.type}
${col.description ? `// Description: ${col.description}` : ''}
${col.units ? `// Units: ${col.units}` : ''}
`).join('')}

// ============================================================
// DESCRIPTIVE STATISTICS
// ============================================================

// Distribution analysis
Distribution(
  Continuous Distribution(
    Column(dt, "${dataset.columns[0]?.name || 'Column 1'}"),
    Quantiles(1),
    Summary Statistics(1)
  ),
  By(""),
  SendToReport(
    Dispatch({}, "Distributions", OutlineBox, {Set Title("Descriptive Statistics")})
  )
);

// ============================================================
// VISUALIZATIONS
// ============================================================

// Histogram with capabilities
Graph Builder(
  Variables(X(:${dataset.columns[0]?.name || 'Column 1'})),
  Elements(Histogram(X)),
  SendToReport(
    Dispatch({}, "Graph Builder", OutlineBox, {Set Title("Distribution Histogram")})
  )
);

// Box plot
Graph Builder(
  Variables(Y(:${dataset.columns[0]?.name || 'Column 1'})),
  Elements(Box Plot(Y)),
  SendToReport(
    Dispatch({}, "Graph Builder", OutlineBox, {Set Title("Box Plot")})
  )
);

// Scatter plot matrix (if multiple numeric columns)
Multivariate(
  Y(${dataset.columns.filter(c => c.type === 'numeric').slice(0, 5).map(c => `:${c.name}`).join(', ')}),
  Scatterplot Matrix(
    "Corr Hidden"
  )
);

${results.capability ? generateJSLCapabilityAnalysis(dataset) : ''}

${results.controlChart ? generateJSLControlChart(dataset) : ''}

${results.regression ? generateJSLRegression(dataset) : ''}

${results.anova ? generateJSLANOVA(dataset) : ''}

// ============================================================
// SIX SIGMA REPORT
// ============================================================

// Create summary report
New Window("Six Sigma Summary",
  Outline Box("Analysis Summary",
    Text Box("Dataset: ${dataset.name}"),
    Text Box("Samples: ${dataset.rows.length}"),
    Text Box("Variables: ${dataset.columns.length}"),
    Text Box("Date: ${new Date().toLocaleString()}"),
    ${results.capability ? `
    Text Box(""),
    Text Box("Capability Results:"),
    Text Box("  Cp: ${results.capability.cp.toFixed(3)}"),
    Text Box("  Cpk: ${results.capability.cpk.toFixed(3)}"),
    Text Box("  Sigma Level: ${results.capability.sigmaLevel.toFixed(2)}"),
    ` : ''}
  )
);

// ============================================================
// SAVE OUTPUT
// ============================================================

// Save data table
Save(dt, "$DOCUMENTS/${dataset.name.replace(/\s+/g, '_')}.jmp");

// Save journal (manual step: File > Save > Save Journal)

Write("\\!NSix Sigma Analysis Complete\\!N");
Write("Check Reports window for all analyses.\\!N");
`;
}

function generateJSLCapabilityAnalysis(dataset: Dataset): string {
  return `
// ============================================================
// PROCESS CAPABILITY ANALYSIS
// ============================================================

// Distribution with capability
capability_dist = Distribution(
  Continuous Distribution(
    Column(dt, "${dataset.columns[0]?.name || 'Column 1'}"),
    Quantiles(1),
    Summary Statistics(1),
    Capability Analysis(
      Capability Box Plot(1),
      USL(100),    // Modify as needed
      LSL(0),      // Modify as needed
      Target(50),  // Modify as needed
      Sigma(3),
      Capability Index Pp(1),
      Capability Index Ppk(1),
      Capability Index Cpm(1),
      Z Bench(1),
      ZLSL(1),
      ZUSL(1),
      PCI(1),
      Cpk(1),
      Cp(1)
    ),
    Fit Distribution(Normal)
  ),
  By(""),
  SendToReport(
    Dispatch({}, "Distributions", OutlineBox, {Set Title("Process Capability Analysis")})
  )
);

// Capability Sixpack
Process Capability(
  Process(${dataset.columns[0]?.name || 'Column 1'}),
  Objective Limits(LSL(0), USL(100), Target(50)),
  Individual Detail Reports(1),
  Capability Box Plot(1),
  Goal Plot(1),
  Capability Index Plot(1),
  Normal Quantile Plot(1)
);

// Create capability summary table
cap_summary = dt << Summary(
  Mean(${dataset.columns[0]?.name || 'Column 1'}),
  Std Dev(${dataset.columns[0]?.name || 'Column 1'}),
  Min(${dataset.columns[0]?.name || 'Column 1'}),
  Max(${dataset.columns[0]?.name || 'Column 1'})
);
`;
}

function generateJSLControlChart(dataset: Dataset): string {
  return `
// ============================================================
// CONTROL CHARTS
// ============================================================

// Individual Measurement Chart (I-MR)
Control Chart Builder(
  Show Two Shewhart Charts(0),
  Show Control Panel(0),
  Variables(
    Y(:${dataset.columns[0]?.name || 'Column 1'}),
    Phase(:),
    Sample Label(:)
  ),
  Chart(
    Position(1),
    Limits(
      Sigma(3),
      Show Center Line(1),
      Show Control Limits(1)
    ),
    Individual Measurement Chart
  ),
  Chart(
    Position(2),
    Limits(
      Sigma(3),
      Show Center Line(1),
      Show Control Limits(1)
    ),
    Moving Range Chart
  ),
  SendToReport(
    Dispatch({}, "Control Chart Builder", OutlineBox, {Set Title("I-MR Control Chart")})
  )
);

// Control Chart with Western Electric Rules
Control Chart(
  Sample Label(:),
  KSigma(3),
  Chart Col(
    :${dataset.columns[0]?.name || 'Column 1'},
    Individual Measurement(
      Test 1(1),
      Test 2(1),
      Test 3(1),
      Test 4(1),
      Test 5(1),
      Test 6(1),
      Test 7(1),
      Test 8(1)
    )
  )
);

// Zone Control Chart
Control Chart(
  Sample Label(:),
  KSigma(3),
  Chart Col(
    :${dataset.columns[0]?.name || 'Column 1'},
    Individual Measurement(
      Zone Colors(1),
      Zone A Tests(2),
      Zone B Tests(4),
      Zone C Tests(8)
    )
  )
);
`;
}

function generateJSLRegression(dataset: Dataset): string {
  return `
// ============================================================
// REGRESSION ANALYSIS
// ============================================================

// Fit Model (requires multiple columns)
// Uncomment and modify column names as needed

/*
Fit Model(
  Y(:Response),
  Effects(:Predictor1, :Predictor2),
  Personality("Standard Least Squares"),
  Emphasis("Minimal Report"),
  Run(
    :Response << {Summary of Fit(1), Analysis of Variance(1), Parameter Estimates(1), 
                  Effect Details(0), Lack of Fit(0), Marginal Model Profiler(0), 
                  Conditional Model Profiler(0), Leverage Plots(0), 
                  Actual by Predicted(1), Residual by Predicted Plot(1), 
                  Residual by Row Plot(1), Assess Normality(1), Box Cox Transformations(0)}
  )
);
*/

// Bivariate analysis (simple regression)
Bivariate(
  Y(:${dataset.columns[1]?.name || dataset.columns[0]?.name || 'Column 1'}),
  X(:${dataset.columns[0]?.name || 'Column 1'}),
  Fit Where(
    Fit Line({Line Color({213, 72, 87})})
  ),
  SendToReport(
    Dispatch({}, "Bivariate Fit", OutlineBox, {Set Title("Regression Analysis")})
  )
);

// Correlation analysis
Multivariate(
  Y(${dataset.columns.filter(c => c.type === 'numeric').slice(0, 5).map(c => `:${c.name}`).join(', ')}),
  Estimation Method("Row-wise"),
  Matrix Format("Square Symmetric"),
  Scatterplot Matrix(0),
  Correlation Multivariate(0),
  Inverse Correlations(0),
  Partial Correlations(0),
  Covariance Matrix(0),
  Pairwise Correlations(0)
);
`;
}

function generateJSLANOVA(_dataset: Dataset): string {
  // Parameter kept for API consistency
  return `
// ============================================================
// ANOVA
// ============================================================

// Fit Model for ANOVA (requires categorical column)
// Uncomment and modify as needed

/*
Fit Model(
  Y(:Measurement),
  Effects(:Group),
  Personality("Standard Least Squares"),
  Emphasis("Effect Leverage"),
  Run(
    :Measurement << {Summary of Fit(1), Analysis of Variance(1), Parameter Estimates(1), 
                     Effect Details(1), Lack of Fit(0), Marginal Model Profiler(0), 
                     Conditional Model Profiler(0), Leverage Plots(1), 
                     Actual by Predicted(0), Residual by Predicted Plot(0)}
  ),
  SendToReport(
    Dispatch({"Analysis of Variance"}, "Parameter Estimates", OutlineBox, {Close(0)})
  )
);
*/

// Oneway ANOVA
// Uncomment with actual column names

/*
Oneway(
  Y(:Measurement),
  X(:Group),
  All Graphs(0),
  Means Diamonds(1),
  Comparison Circles(0),
  X Axis Proportional(0),
  Grand Mean(0),
  Box Plots(1),
  Mean Error Bars(0),
  Std Dev Lines(0),
  Points Spread(0),
  Points Jittered(1),
  By(:),
  Mean Diamonds and X-Axis Proportional(0),
  Mean Lines(0),
  Mean CI Lines(0),
  Mean Connect Points(0),
  Mean of Means(0),
  Mean of Means Connect Points(0)
);
*/

// Variability Chart
// Uncomment with actual column names

/*
Variability Chart(
  Y(:Measurement),
  X(:Group),
  Std Dev Chart(1),
  Points(1),
  Range Chart(0)
);
*/
`;
}

function generateJMPDataFile(dataset: Dataset): string {
  return `# JMP Data File - ${dataset.name}
# Import into JMP using: File > Open
# Or copy data and use: File > New > Data Table

# Column Information:
${dataset.columns.map((col, idx) => `# ${idx + 1}. ${col.name} (${col.type})${col.units ? ` [${col.units}]` : ''}${col.description ? ` - ${col.description}` : ''}`).join('\n')}

# Data (CSV format - save as .csv and open in JMP):
${dataset.columns.map(col => col.name).join(',')}
${dataset.rows.slice(0, 200).map(row => 
  row.map(cell => {
    if (cell === null || cell === undefined) return '';
    if (typeof cell === 'string') return `"${cell}"`;
    return String(cell);
  }).join(',')
).join('\n')}
${dataset.rows.length > 200 ? `
# ... (${dataset.rows.length - 200} more rows)` : ''}
`;
}

function generateJMPJournal(dataset: Dataset, results: AnalysisResults): string {
  return `// JMP Journal Template - Six Sigma Analysis
// Run this script to create an organized analysis journal

journal = New Window("Six Sigma Analysis: ${dataset.name}",
  V List Box(
    Text Box("Six Sigma Analysis Report", <<Font Size(16), <<Set Font Style("Bold"),
    Text Box("Dataset: ${dataset.name}"),
    Text Box("Date: ${new Date().toLocaleString()}"),
    Text Box("Samples: ${dataset.rows.length}"),
    Text Box("Variables: ${dataset.columns.length}"),
    
    Spacer Box(Size(0, 20)),
    
    Outline Box("1. Data Summary",
      Text Box("Variables analyzed:"),
      ${dataset.columns.map(col => `Text Box("  • ${col.name}${col.description ? ` - ${col.description}` : ''}"),`).join('\n      ')}
    ),
    
    Spacer Box(Size(0, 10)),
    
    Outline Box("2. Descriptive Statistics",
      Text Box("[Run Distribution analysis and capture results here]")
    ),
    
    ${results.capability ? `
    Spacer Box(Size(0, 10)),
    
    Outline Box("3. Process Capability",
      Text Box("Specification Limits:"),
      Text Box("  USL: ${results.capability.usl ?? 'Not set'}"),
      Text Box("  LSL: ${results.capability.lsl ?? 'Not set'}"),
      Text Box("  Target: ${results.capability.target ?? 'Not set'}"),
      Text Box(""),
      Text Box("Capability Indices:"),
      Text Box("  Cp: ${results.capability.cp.toFixed(3)}"),
      Text Box("  Cpk: ${results.capability.cpk.toFixed(3)}"),
      Text Box("  Cpu: ${results.capability.cpu.toFixed(3)}"),
      Text Box("  Cpl: ${results.capability.cpl.toFixed(3)}"),
      Text Box(""),
      Text Box("Performance Metrics:"),
      Text Box("  Sigma Level: ${results.capability.sigmaLevel.toFixed(2)}"),
      Text Box("  DPMO: ${results.capability.dpmo.toLocaleString()}"),
    ),
    ` : ''}
    
    ${results.controlChart ? `
    Spacer Box(Size(0, 10)),
    
    Outline Box("4. Control Chart Analysis",
      Text Box("Chart Type: I-MR"),
      Text Box("Center Line: ${results.controlChart.centerLine}"),
      Text Box("UCL: ${results.controlChart.ucl}"),
      Text Box("LCL: ${results.controlChart.lcl}"),
      Text Box(""),
      Text Box("Control Status: [Stable/Unstable - to be determined]")
    ),
    ` : ''}
    
    ${results.regression ? `
    Spacer Box(Size(0, 10)),
    
    Outline Box("5. Regression Analysis",
      Text Box("R²: ${results.regression.rSquared.toFixed(4)}"),
      Text Box("Adjusted R²: ${results.regression.adjRSquared.toFixed(4)}"),
      Text Box(""),
      Text Box("Regression Equation:"),
      Text Box("  ${results.regression.equation}")
    ),
    ` : ''}
    
    Spacer Box(Size(0, 20)),
    
    Outline Box("Conclusions & Next Steps",
      Text Box("1. [Add key findings]"),
      Text Box("2. [Add recommendations]"),
      Text Box("3. [Add next actions]")
    ),
    
    Spacer Box(Size(0, 20)),
    
    Button Box("Save Journal",
      <<Script(
        journal << Save Journal("$DOCUMENTS/${dataset.name.replace(/\s+/g, '_')}_Analysis.jrn");
        Write("\\!NJournal saved.\\!N");
      )
    )
  )
);

journal;
`;
}

/**
 * Generate JMP add-in script for reusable Six Sigma tools
 */
export function generateJMPAddIn(): string {
  return `// Six Sigma Tools for JMP
// Save this as an Add-In for reusable Six Sigma analysis tools

// Main menu definition
six_sigma_menu = New Menu("Six Sigma Tools",
  Menu Item("Distribution with Capability",
    <<Script(
      dt = Current Data Table();
      col = Column Dialog(Col = ColList("Select column for analysis:"));
      
      Distribution(
        Continuous Distribution(
          Column(dt, col[1]),
          Quantiles(1),
          Summary Statistics(1),
          Capability Analysis(1)
        )
      );
    )
  ),
  Menu Item("I-MR Control Chart",
    <<Script(
      dt = Current Data Table();
      col = Column Dialog(Col = ColList("Select measurement column:"));
      
      Control Chart Builder(
        Variables(Y(col[1])),
        Chart(Individual Measurement),
        Chart(Moving Range Chart)
      );
    )
  ),
  Menu Item("Process Capability Summary",
    <<Script(
      dt = Current Data Table();
      col = Column Dialog(Col = ColList("Select column(s):"));
      
      Process Capability(
        Process(col),
        Capability Box Plot(1),
        Goal Plot(1),
        Capability Index Plot(1)
      );
    )
  ),
  Menu Item("Capability Sixpack",
    <<Script(
      dt = Current Data Table();
      dlg = Dialog(
        Text Box("Select column for Capability Sixpack:"),
        H List Box(
          Text Box("Column:"),
          col_list = List Box(dt << Get Column Names("Continuous"))
        ),
        Text Box("Specification Limits:"),
        H List Box(Text Box("LSL:"), lsl = Edit Number(0)),
        H List Box(Text Box("USL:"), usl = Edit Number(100)),
        H List Box(Text Box("Target:"), target = Edit Number(50)),
        Button Box("OK", <<Return({col_list, lsl, usl, target})),
        Button Box("Cancel", <<Return({}))
      );
      
      if(N Items(dlg) > 0,
        Process Capability(
          Process(dlg["col_list"][1]),
          Objective Limits(LSL(dlg["lsl"]), USL(dlg["usl"]), Target(dlg["target"])),
          Individual Detail Reports(1),
          Capability Box Plot(1),
          Goal Plot(1),
          Normal Quantile Plot(1)
        )
      );
    )
  ),
  Menu Item("-"),  // Separator
  Menu Item("Gage R&R (Short Form)",
    <<Script(
      Write("\\!NNote: Requires measurement data with Part and Operator columns.\\!N");
      Write("Use: Analyze > Quality and Process > Variability / Attribute Gauge Chart\\!N");
    )
  ),
  Menu Item("Pareto Chart",
    <<Script(
      dt = Current Data Table();
      col = Column Dialog(
        Y = ColList("Select cause column:"),
        Freq = ColList("Select frequency column (optional):")
      );
      
      if(N Items(col["Freq"]) > 0,
        Graph Builder(
          Variables(X(col["Y"][1]), Y(col["Freq"][1])),
          Elements(Bar(X, Y, Summary Statistic("Sum"), Label(Label Values))),
          Ordering(Me(Y, Descending))
        ),
        Graph Builder(
          Variables(X(col["Y"][1])),
          Elements(Histogram(X))
        )
      );
    )
  )
);

// Add menu to main menu bar
Insert Into( Menu( "Analyze" ), -1, six_sigma_menu );

Write("\\!NSix Sigma Tools menu added to Analyze menu.\\!N");
`;
}

/**
 * Generate JMP command reference
 */
export function generateJMPCommandReference(): string {
  return `# JMP Scripting Language (JSL) Reference for Six Sigma

## Data Operations

| Command | Description |
|---------|-------------|
| New Table() | Create new data table |
| Open() | Open data file |
| Save() | Save data table |
| Current Data Table() | Get active table |
| Column() | Reference column |

## Analysis Platforms

| Platform | Description |
|----------|-------------|
| Distribution() | Descriptive stats & capability |
| Fit Model() | Regression & ANOVA |
| Control Chart() | SPC charts |
| Control Chart Builder() | Interactive charts |
| Process Capability() | Capability analysis |
| Graph Builder() | Custom visualizations |

## Distribution Options

\`\`\`
Distribution(
  Continuous Distribution(
    Column(dt, "Measurement"),
    Quantiles(1),
    Summary Statistics(1),
    Capability Analysis(
      USL(100),
      LSL(0),
      Target(50)
    ),
    Fit Distribution(Normal)
  )
);
\`\`\`

## Control Chart Options

\`\`\`
Control Chart(
  Sample Label(:Time),
  KSigma(3),
  Chart Col(
    :Measurement,
    Individual Measurement(
      Test 1(1),
      Test 2(1),
      Test 3(1)
    )
  )
);
\`\`\`

## Process Capability Options

\`\`\`
Process Capability(
  Process(Measurement),
  Objective Limits(LSL(0), USL(100), Target(50)),
  Individual Detail Reports(1),
  Capability Box Plot(1),
  Goal Plot(1),
  Capability Index Plot(1)
);
\`\`\`

## Graph Builder Examples

### Histogram
\`\`\`
Graph Builder(
  Variables(X(:Measurement)),
  Elements(Histogram(X))
);
\`\`\`

### Box Plot
\`\`\`
Graph Builder(
  Variables(Y(:Measurement), X(:Group)),
  Elements(Box Plot(X, Y))
);
\`\`\`

### Scatter Plot with Regression
\`\`\`
Graph Builder(
  Variables(X(:X), Y(:Y)),
  Elements(Points(X, Y), Smoother(X, Y))
);
\`\`\`

## Useful Functions

| Function | Description |
|----------|-------------|
| Mean() | Calculate mean |
| Std Dev() | Calculate standard deviation |
| Col Mean() | Column mean |
| Col Std Dev() | Column standard deviation |
| N Rows() | Number of rows |
| N Cols() | Number of columns |

## Tips

1. Use << to send messages to objects
2. Use :: for global variables
3. Use : for column references
4. Use "Name" for column names with spaces

## Example Workflow

\`\`\`
// Load data
dt = Open("$DOCUMENTS/data.jmp");

// Run distribution
dist = dt << Distribution(
  Continuous Distribution(Column(:Measurement))
);

// Save report
dist << Save Report("$DOCUMENTS/analysis.rpt");
\`\`\`
`;
}
