/**
 * Minitab Export Generator
 * 
 * Generates Minitab-compatible session commands and data files
 */

import type { Dataset, AnalysisResults, ExportConfig } from '../types';

export interface MinitabExport {
  sessionCommands: string;
  dataFile: string;
  projectNotes: string;
  filename: string;
}

/**
 * Generate Minitab session commands for complete analysis
 */
export function generateMinitabExport(
  dataset: Dataset,
  results: AnalysisResults,
  config: ExportConfig
): MinitabExport {
  const sessionCommands = generateSessionCommands(dataset, results, config);
  const dataFile = generateMinitabDataFile(dataset);
  const projectNotes = generateProjectNotes(dataset, results);
  
  return {
    sessionCommands,
    dataFile,
    projectNotes,
    filename: `${dataset.name.replace(/\s+/g, '_')}_Minitab.txt`,
  };
}

function generateSessionCommands(
  dataset: Dataset,
  results: AnalysisResults,
  config: ExportConfig
): string {
  let commands = `# Minitab Session Commands
# Generated by Six Sigma Training Platform
# Date: ${new Date().toLocaleString()}
# Project: ${dataset.name}

# ============================================================
# DATA IMPORT AND SETUP
# ============================================================

# Clear any existing data
Erase C1-C100

# Import data from worksheet
# Note: Paste data into worksheet columns C1-C${dataset.columns.length}

# Set column names
${dataset.columns.map((col, idx) => `Name C${idx + 1} "${col.name}"`).join('\n')}

# ============================================================
# DESCRIPTIVE STATISTICS
# ============================================================

Describe C1-C${dataset.columns.length};
  Statistics All;
  GIndices.

# Store statistics
Statistics C1;
  Mean 'Mean';
  StDev 'StDev';
  Minimum 'Min';
  Maximum 'Max';
  N 'N';
  Q1 'Q1';
  Median 'Median';
  Q3 'Q3'.

`;

  // Capability Analysis
  if (results.capability) {
    commands += `
# ============================================================
# PROCESS CAPABILITY ANALYSIS
# ============================================================

Capa C1;
  USL ${results.capability.usl ?? 100};
  LSL ${results.capability.lsl ?? 0};
  Target ${results.capability.target ?? 50};
  PPM;
  Within;
  Overall;
  Benchmark 6;
  CStat.

# Normality test for capability
NormTest C1;
  Ryan.

# Capability Sixpack
CapaSixpack C1;
  LSL ${results.capability.lsl ?? 0};
  USL ${results.capability.usl ?? 100}.

`;
  }

  // Control Chart
  if (results.controlChart) {
    commands += `
# ============================================================
# CONTROL CHARTS
# ============================================================

# I-MR Chart (Individual and Moving Range)
Chart C1;
  IChart;
  MRChart;
  Tests 1 2 3.

# If subgroup size > 1, use Xbar-R
# Chart C1;
#   XBarChart;
#   RChart;
#   GSample C2;
#   Tests 1 2 3.

# Control Chart Rules
Chart C1;
  IChart;
  Tests 1 2 3 4 5 6 7 8.

`;
  }

  // Regression Analysis
  if (results.regression) {
    const responseCol = dataset.columns.length >= 2 ? 2 : 1;
    const predictorCol = 1;
    
    commands += `
# ============================================================
# REGRESSION ANALYSIS
# ============================================================

# Simple Linear Regression
Regress C${responseCol} 1 C${predictorCol};
  Constant;
  Predictors;
  RStorage RESI FITS;
  MSEquation.

# Residual analysis
Residuals 'RESI' 'FITS'.

# Four-in-one residual plots
ResPlot 'RESI' 'FITS'.

`;
  }

  // ANOVA
  if (results.anova) {
    commands += `
# ============================================================
# ANOVA
# ============================================================

# One-way ANOVA (if categorical column exists)
Oneway C1 C2;
  Tukey 5;
  GBoxplot.

# General Linear Model (if multiple factors)
# GLM C1 = C2 C3 C2*C3;
#   Random C2;
#   Means C2 C3.

`;
  }

  // Distribution Analysis
  commands += `
# ============================================================
# DISTRIBUTION ANALYSIS
# ============================================================

# Histogram with fit
Hist C1;
  Normal;
  Fit.

# Probability plot
ProbPlot C1;
  Normal;
  GReference.

# Boxplot
Boxplot C1;
  Outlier.

# ============================================================
# SIX SIGMA REPORT
# ============================================================

# Generate summary report
Note "=== Six Sigma Analysis Summary ==="
Note "Project: ${dataset.name}"
Note "Samples: ${dataset.rows.length}"
Note "Date: ${new Date().toLocaleDateString()}"

`;

  // Add macro definition if requested
  if (config.includeMacros) {
    commands += generateMinitabMacro();
  }

  return commands;
}

function generateMinitabDataFile(dataset: Dataset): string {
  let content = `# Minitab Data File
# ${dataset.name}
# Columns: ${dataset.columns.map(c => c.name).join(', ')}
# Rows: ${dataset.rows.length}
#
`;
  
  // Header row
  content += dataset.columns.map(col => col.name).join('\t') + '\n';
  
  // Data rows
  dataset.rows.forEach(row => {
    content += row.map(cell => {
      if (cell === null || cell === undefined) return '*';
      if (typeof cell === 'number') return cell.toFixed(6);
      return String(cell);
    }).join('\t') + '\n';
  });
  
  return content;
}

function generateProjectNotes(dataset: Dataset, results: AnalysisResults): string {
  let notes = `Minitab Project: ${dataset.name}
Generated: ${new Date().toLocaleString()}

DATA SUMMARY
============
Dataset: ${dataset.name}
Rows: ${dataset.rows.length}
Columns: ${dataset.columns.length}
Description: ${dataset.metadata.description}

COLUMNS
=======
${dataset.columns.map((col, idx) => 
  `C${idx + 1}: ${col.name} (${col.type})${col.units ? ` [${col.units}]` : ''}${col.description ? ` - ${col.description}` : ''}`
).join('\n')}

`;

  if (results.statistics) {
    notes += `DESCRIPTIVE STATISTICS
======================
Count: ${results.statistics.count}
Mean: ${results.statistics.mean.toFixed(4)}
Std Dev: ${results.statistics.stdDev.toFixed(4)}
Min: ${results.statistics.min.toFixed(4)}
Max: ${results.statistics.max.toFixed(4)}

`;
  }

  if (results.capability) {
    notes += `CAPABILITY ANALYSIS
===================
Cp: ${results.capability.cp.toFixed(3)}
Cpk: ${results.capability.cpk.toFixed(3)}
Sigma Level: ${results.capability.sigmaLevel.toFixed(2)}
DPMO: ${results.capability.dpmo.toLocaleString()}
USL: ${results.capability.usl ?? 'Not set'}
LSL: ${results.capability.lsl ?? 'Not set'}

`;
  }

  notes += `ANALYSIS CHECKLIST
==================
□ Data imported correctly
□ Check for missing values
□ Verify measurement units
□ Confirm subgroup structure
□ Validate specification limits
□ Review control chart rules
□ Check normality assumption
□ Document findings

INTERPRETATION GUIDE
====================
Cp > 1.33: Process is capable
Cpk > 1.33: Process is capable and centered
Cpk < 1.00: Process needs improvement
Sigma Level > 4.5: World-class performance

NEXT STEPS
==========
1. Review control charts for stability
2. Investigate out-of-control points
3. Validate normality assumption
4. Document improvement actions
5. Implement control plan
`;

  return notes;
}

function generateMinitabMacro(): string {
  return `
# ============================================================
# MINITAB MACRO: SixSigmaAnalysis.mac
# ============================================================
# Usage: %SixSigmaAnalysis C1 "USL" "LSL"
# ============================================================

Macro SixSigmaAnalysis DataCol USL LSL
MColumn DataCol Residuals Fitted ResStd
MConstant N MeanVal StDevVal MinVal MaxVal CpVal CpkVal

# Descriptive statistics
Let N = Count(DataCol)
Let MeanVal = Mean(DataCol)
Let StDevVal = STDEV(DataCol)
Let MinVal = Minimum(DataCol)
Let MaxVal = Maximum(DataCol)

# Calculate capability
Let CpVal = (USL - LSL) / (6 * StDevVal)
Let CpkVal = Minimum((USL - MeanVal)/(3*StDevVal), (MeanVal-LSL)/(3*StDevVal))

# Print summary
Note ""
Note "=== Six Sigma Analysis Results ==="
Note "Sample Size:"
Print N
Note "Mean:"
Print MeanVal
Note "Std Dev:"
Print StDevVal
Note "Cp:"
Print CpVal
Note "Cpk:"
Print CpkVal
Note ""

# Generate control chart
Chart DataCol;
  IChart;
  Tests 1 2 3.

# Normality test
NormTest DataCol.

# Capability analysis
Capa DataCol;
  USL USL;
  LSL LSL;
  PPM.

EndMacro
`;
}

/**
 * Generate Minitab assistant guide
 */
export function generateMinitabGuide(): string {
  return `# Minitab Analysis Guide

## Getting Started

### 1. Import Data
1. Open Minitab Statistical Software
2. Copy data from the generated data file
3. Paste into Minitab worksheet
4. Verify column names are correct

### 2. Run Session Commands
1. Go to **Editor > Command Line Editor**
2. Paste the session commands
3. Click "Submit Commands"

### 3. Or Use Menu Interface

#### Descriptive Statistics
- **Stat > Basic Statistics > Display Descriptive Statistics**
- Select variables
- Click Statistics to choose which statistics to display

#### Process Capability
- **Stat > Quality Tools > Capability Analysis > Normal**
- Select data column
- Enter LSL and USL
- Click OK

#### Control Charts
- **Stat > Control Charts > Variables Charts for Individuals > I-MR**
- Select data column
- Click I-MR Options > Tests to run all tests

#### Regression
- **Stat > Regression > Regression > Fit Regression Model**
- Select response variable
- Select predictor variables
- Click OK

## Common Commands Reference

### Data Manipulation
| Task | Command |
|------|---------|
| Sort data | \`Sort C1 C2\` |
| Subset data | \`Copy C1 C2; Where C3 = "A".\` |
| Stack columns | \`Stack C1 C2 C3.\` |
| Transpose | \`Transpose C1-C5.\` |

### Statistics
| Analysis | Command |
|----------|---------|
| Mean | \`Mean C1\` |
| Std Dev | \`StDev C1\` |
| Correlation | \`Correlation C1 C2\` |
| T-Test | \`TTest C1; Mu 50.\` |

### Quality Tools
| Tool | Command |
|------|---------|
| Capability | \`Capa C1; USL 100; LSL 0.\` |
| Control Chart | \`Chart C1; IChart.\` |
| Pareto | \`Pareto C1.\` |
| Gage R&R | \`GStudy C1 = C2 C3.\` |

## Output Interpretation

### Capability Indices
- **Cp**: Potential capability (tolerance width / process width)
- **Cpk**: Actual capability (minimum of Cpu and Cpl)
- **Pp/Ppk**: Overall performance (includes between-subgroup variation)

### Control Charts
- **Test 1**: Point beyond 3σ
- **Test 2**: 9 points in a row on same side of center line
- **Test 3**: 6 points in a row trending up or down

### Regression Output
- **S**: Standard deviation of residuals
- **R-sq**: Percentage of variation explained by model
- **R-sq(adj)**: R-sq adjusted for number of predictors
- **VIF**: Variance inflation factor (multicollinearity check)

## Tips for Six Sigma Projects

1. **Always check normality** before capability analysis
2. **Verify measurement system** with Gage R&R study
3. **Use control charts** to ensure process stability
4. **Document your analysis** in the Project Manager
5. **Save your project** frequently with descriptive names

## Keyboard Shortcuts

- **Ctrl+1**: Assistant
- **Ctrl+D**: Display Data
- **Ctrl+E**: Command Line Editor
- **Ctrl+G**: Generate Report
- **Ctrl+M**: Project Manager
- **Ctrl+S**: Save Project
`;
}
