/**
 * Python Export Generator
 * 
 * Generates complete Python/Jupyter notebook code for Six Sigma analysis
 */

import type { Dataset, AnalysisResults, ExportConfig } from '../types';

export interface PythonExport {
  script: string;
  notebook: string;
  requirements: string;
  readme: string;
  filename: string;
}

/**
 * Generate complete Python analysis script
 */
export function generatePythonExport(
  dataset: Dataset,
  results: AnalysisResults,
  _config: ExportConfig
): PythonExport {
  const script = generateAnalysisScript(dataset, results, _config);
  const notebook = generateJupyterNotebook(dataset, results, _config);
  const requirements = generateRequirements();
  const readme = generatePythonReadme(dataset);
  
  return {
    script,
    notebook,
    requirements,
    readme,
    filename: `${dataset.name.replace(/\s+/g, '_')}_analysis.py`,
  };
}

function generateAnalysisScript(
  dataset: Dataset,
  results: AnalysisResults,
  _config: ExportConfig
): string {
  return `# Six Sigma Analysis - Python Script
# Generated by Six Sigma Training Platform
# Date: ${new Date().toLocaleString()}
# Dataset: ${dataset.name}

# ============================================================
# IMPORTS
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy.stats import norm, probplot
import warnings
warnings.filterwarnings('ignore')

# Six Sigma specific imports
try:
    import statsmodels.api as sm
    from statsmodels.stats.anova import AnovaRM
    from statsmodels.stats.diagnostic import normal_ad
    STATSMODELS_AVAILABLE = True
except ImportError:
    STATSMODELS_AVAILABLE = False
    print("statsmodels not available - some features disabled")

try:
    from sklearn.linear_model import LinearRegression
    from sklearn.metrics import r2_score, mean_squared_error
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False
    print("scikit-learn not available - regression features disabled")

# ============================================================
# CONFIGURATION
# ============================================================

# Set plotting style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 10

# Six Sigma constants
LSL = ${results.capability?.lsl ?? 'None'}  # Lower Specification Limit
USL = ${results.capability?.usl ?? 'None'}  # Upper Specification Limit
TARGET = ${results.capability?.target ?? 'None'}  # Target value

# ============================================================
# DATA LOADING
# ============================================================

# Create DataFrame from analysis data
data_dict = {
${dataset.columns.map((col, idx) => `    '${col.name}': [${dataset.rows.slice(0, 20).map(r => {
    const val = r[idx];
    if (val === null || val === undefined) return 'np.nan';
    if (typeof val === 'string') return `'${val}'`;
    return String(val);
  }).join(', ')}${dataset.rows.length > 20 ? ', ...' : ''}],`).join('\n')}
}

df = pd.DataFrame(data_dict)

# Load full dataset (use CSV import for large datasets)
# df = pd.read_csv('${dataset.name.replace(/\s+/g, '_')}_data.csv')

print("Dataset Overview:")
print(f"Shape: {df.shape}")
print(f"\\nFirst few rows:")
print(df.head())
print(f"\\nData Types:")
print(df.dtypes)
print(f"\\nMissing Values:")
print(df.isnull().sum())

# ============================================================
# DESCRIPTIVE STATISTICS
# ============================================================

print("\\n" + "="*60)
print("DESCRIPTIVE STATISTICS")
print("="*60)

# Select numeric column for analysis
numeric_cols = df.select_dtypes(include=[np.number]).columns
if len(numeric_cols) > 0:
    y = df[numeric_cols[0]]
    print(f"\\nAnalyzing column: {numeric_cols[0]}")
else:
    y = df.iloc[:, 0]
    print(f"\\nAnalyzing column: {df.columns[0]}")

# Calculate statistics
n = len(y)
mean = y.mean()
median = y.median()
std = y.std()
min_val = y.min()
max_val = y.max()
q1 = y.quantile(0.25)
q3 = y.quantile(0.75)
skewness = y.skew()
kurt = y.kurtosis()

print(f"\\nCount:        {n}")
print(f"Mean:         {mean:.4f}")
print(f"Median:       {median:.4f}")
print(f"Std Dev:      {std:.4f}")
print(f"Min:          {min_val:.4f}")
print(f"Max:          {max_val:.4f}")
print(f"Q1:           {q1:.4f}")
print(f"Q3:           {q3:.4f}")
print(f"IQR:          {q3-q1:.4f}")
print(f"Skewness:     {skewness:.4f}")
print(f"Kurtosis:     {kurt:.4f}")

# Summary statistics table
desc_stats = df.describe()
print(f"\\nFull Summary Statistics:")
print(desc_stats)

${results.capability ? generatePythonCapabilityAnalysis() : ''}

${results.regression ? generatePythonRegressionAnalysis() : ''}

${results.controlChart ? generatePythonControlChart() : ''}

${results.anova ? generatePythonANOVA() : ''}

# ============================================================
# VISUALIZATIONS
# ============================================================

def create_six_sigma_report():
    """Generate comprehensive Six Sigma visualization report"""
    fig = plt.figure(figsize=(16, 12))
    
    # Histogram with normal fit
    ax1 = plt.subplot(2, 3, 1)
    ax1.hist(y, bins=30, density=True, alpha=0.7, color='steelblue', edgecolor='black')
    if not pd.isna(std) and std > 0:
        x_norm = np.linspace(y.min(), y.max(), 100)
        ax1.plot(x_norm, norm.pdf(x_norm, mean, std), 'r-', lw=2, label='Normal fit')
    ax1.axvline(mean, color='green', linestyle='--', label=f'Mean={mean:.2f}')
    ax1.set_xlabel('Value')
    ax1.set_ylabel('Density')
    ax1.set_title('Distribution with Normal Fit')
    ax1.legend()
    
    # Box plot
    ax2 = plt.subplot(2, 3, 2)
    bp = ax2.boxplot(y.dropna(), patch_artist=True)
    bp['boxes'][0].set_facecolor('lightblue')
    ax2.set_ylabel('Value')
    ax2.set_title('Box Plot')
    ax2.grid(True, alpha=0.3)
    
    # Q-Q plot
    ax3 = plt.subplot(2, 3, 3)
    probplot(y.dropna(), dist="norm", plot=ax3)
    ax3.set_title('Q-Q Plot (Normality Check)')
    ax3.grid(True, alpha=0.3)
    
    ${results.capability ? `
    # Capability plot
    ax4 = plt.subplot(2, 3, 4)
    ax4.hist(y, bins=30, alpha=0.5, color='gray', edgecolor='black')
    if LSL is not None:
        ax4.axvline(LSL, color='red', linestyle='--', linewidth=2, label=f'LSL={LSL}')
    if USL is not None:
        ax4.axvline(USL, color='red', linestyle='--', linewidth=2, label=f'USL={USL}')
    if TARGET is not None:
        ax4.axvline(TARGET, color='green', linestyle=':', linewidth=2, label=f'Target={TARGET}')
    ax4.axvline(mean, color='blue', linestyle='-', linewidth=2, label=f'Mean={mean:.2f}')
    ax4.set_xlabel('Value')
    ax4.set_ylabel('Frequency')
    ax4.set_title('Process Capability')
    ax4.legend()
    ` : ''}
    
    # Time series plot (if index represents time)
    ax5 = plt.subplot(2, 3, 5)
    ax5.plot(y.index, y, 'b-', alpha=0.7)
    ax5.axhline(mean, color='r', linestyle='--', label='Mean')
    if not pd.isna(std):
        ax5.axhline(mean + 2*std, color='orange', linestyle=':', alpha=0.7, label='±2σ')
        ax5.axhline(mean - 2*std, color='orange', linestyle=':', alpha=0.7)
    ax5.set_xlabel('Sample')
    ax5.set_ylabel('Value')
    ax5.set_title('Time Series Plot')
    ax5.legend()
    ax5.grid(True, alpha=0.3)
    
    # Summary text
    ax6 = plt.subplot(2, 3, 6)
    ax6.axis('off')
    summary_text = f"""
    SIX SIGMA SUMMARY
    
    Sample Size: {n}
    Mean: {mean:.4f}
    Std Dev: {std:.4f}
    ${results.capability ? `
    Cp: ${results.capability.cp.toFixed(3)}
    Cpk: ${results.capability.cpk.toFixed(3)}
    Sigma Level: ${results.capability.sigmaLevel.toFixed(2)}
    DPMO: ${results.capability.dpmo.toLocaleString()}
    ` : ''}
    """
    ax6.text(0.1, 0.5, summary_text, fontsize=12, verticalalignment='center',
             family='monospace', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    plt.tight_layout()
    plt.savefig('six_sigma_analysis.png', dpi=300, bbox_inches='tight')
    print("\\nReport saved as 'six_sigma_analysis.png'")
    plt.show()

# Generate report
if __name__ == "__main__":
    create_six_sigma_report()
    print("\\n✓ Analysis complete!")
`;
}

function generatePythonCapabilityAnalysis(): string {
  return `
# ============================================================
# PROCESS CAPABILITY ANALYSIS
# ============================================================

print("\\n" + "="*60)
print("PROCESS CAPABILITY ANALYSIS")
print("="*60)

if USL is not None and LSL is not None:
    # Calculate capability indices
    cp = (USL - LSL) / (6 * std)
    cpu = (USL - mean) / (3 * std) if std > 0 else np.inf
    cpl = (mean - LSL) / (3 * std) if std > 0 else np.inf
    cpk = min(cpu, cpl)
    
    # Overall capability (Pp, Ppk)
    pp = (USL - LSL) / (6 * y.std(ddof=0))
    ppu = (USL - mean) / (3 * y.std(ddof=0)) if y.std(ddof=0) > 0 else np.inf
    ppl = (mean - LSL) / (3 * y.std(ddof=0)) if y.std(ddof=0) > 0 else np.inf
    ppk = min(ppu, ppl)
    
    # Sigma level and DPMO
    sigma_level = cpk * 3
    z_bench = sigma_level
    dpmo = 2 * (1 - norm.cdf(sigma_level)) * 1000000
    
    print(f"\\nSpecification Limits:")
    print(f"  USL: {USL}")
    print(f"  LSL: {LSL}")
    print(f"  Target: {TARGET}")
    print(f"  Tolerance: {USL - LSL}")
    
    print(f"\\nWithin (Short-term) Capability:")
    print(f"  Cp:  {cp:.3f} {'✓' if cp >= 1.33 else '⚠'}")
    print(f"  Cpk: {cpk:.3f} {'✓' if cpk >= 1.33 else '⚠'}")
    print(f"  Cpu: {cpu:.3f}")
    print(f"  Cpl: {cpl:.3f}")
    
    print(f"\\nOverall (Long-term) Capability:")
    print(f"  Pp:  {pp:.3f}")
    print(f"  Ppk: {ppk:.3f}")
    
    print(f"\\nSigma Metrics:")
    print(f"  Sigma Level: {sigma_level:.2f}")
    print(f"  DPMO: {dpmo:,.0f}")
    print(f"  Yield: {(1 - dpmo/1000000)*100:.4f}%")
    
    # Capability interpretation
    print(f"\\nInterpretation:")
    if cpk >= 1.67:
        print("  → World-class capability (Cpk ≥ 1.67)")
    elif cpk >= 1.33:
        print("  → Capable process (Cpk ≥ 1.33)")
    elif cpk >= 1.0:
        print("  → Marginally capable (1.0 ≤ Cpk < 1.33)")
    else:
        print("  → Process needs improvement (Cpk < 1.0)")
    
    # Normality check for capability validity
    if STATSMODELS_AVAILABLE:
        stat, p_value = normal_ad(y.dropna())
        print(f"\\nNormality Test (Anderson-Darling):")
        print(f"  Statistic: {stat:.4f}")
        print(f"  p-value: {p_value:.4f}")
        print(f"  {'Normal' if p_value > 0.05 else 'Non-normal'} distribution (α=0.05)")
else:
    print("⚠ Specification limits not set. Set USL and LSL for capability analysis.")
`;
}

function generatePythonRegressionAnalysis(): string {
  return `
# ============================================================
# REGRESSION ANALYSIS
# ============================================================

print("\\n" + "="*60)
print("REGRESSION ANALYSIS")
print("="*60)

if SKLEARN_AVAILABLE and len(numeric_cols) >= 2:
    # Prepare data
    X = df[numeric_cols[:-1]]  # All columns except last as predictors
    y_reg = df[numeric_cols[-1]]  # Last column as response
    
    # Fit model
    model = LinearRegression()
    model.fit(X, y_reg)
    
    # Predictions
    y_pred = model.predict(X)
    
    # Metrics
    r2 = r2_score(y_reg, y_pred)
    adj_r2 = 1 - (1 - r2) * (len(y_reg) - 1) / (len(y_reg) - X.shape[1] - 1)
    rmse = np.sqrt(mean_squared_error(y_reg, y_pred))
    
    print(f"\\nModel Summary:")
    print(f"  R²:           {r2:.4f}")
    print(f"  Adjusted R²:  {adj_r2:.4f}")
    print(f"  RMSE:         {rmse:.4f}")
    print(f"  Intercept:    {model.intercept_:.4f}")
    
    print(f"\\nCoefficients:")
    for i, col in enumerate(X.columns):
        print(f"  {col}: {model.coef_[i]:.6f}")
    
    # Regression equation
    equation = f"y = {model.intercept_:.4f}"
    for i, col in enumerate(X.columns):
        sign = "+" if model.coef_[i] >= 0 else ""
        equation += f" {sign} {model.coef_[i]:.4f}*{col}"
    print(f"\\nRegression Equation:")
    print(f"  {equation}")
    
    # Residual analysis
    residuals = y_reg - y_pred
    print(f"\\nResidual Analysis:")
    print(f"  Mean residual: {residuals.mean():.6f}")
    print(f"  Std residual:  {residuals.std():.4f}")
    
    # Plot regression diagnostics
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    
    # Predicted vs Actual
    axes[0, 0].scatter(y_reg, y_pred, alpha=0.6)
    axes[0, 0].plot([y_reg.min(), y_reg.max()], [y_reg.min(), y_reg.max()], 'r--', lw=2)
    axes[0, 0].set_xlabel('Actual')
    axes[0, 0].set_ylabel('Predicted')
    axes[0, 0].set_title('Predicted vs Actual')
    axes[0, 0].grid(True, alpha=0.3)
    
    # Residuals vs Predicted
    axes[0, 1].scatter(y_pred, residuals, alpha=0.6)
    axes[0, 1].axhline(y=0, color='r', linestyle='--')
    axes[0, 1].set_xlabel('Predicted')
    axes[0, 1].set_ylabel('Residuals')
    axes[0, 1].set_title('Residuals vs Predicted')
    axes[0, 1].grid(True, alpha=0.3)
    
    # Histogram of residuals
    axes[1, 0].hist(residuals, bins=20, edgecolor='black', alpha=0.7)
    axes[1, 0].set_xlabel('Residual')
    axes[1, 0].set_ylabel('Frequency')
    axes[1, 0].set_title('Distribution of Residuals')
    axes[1, 0].grid(True, alpha=0.3)
    
    # Q-Q plot of residuals
    probplot(residuals, dist="norm", plot=axes[1, 1])
    axes[1, 1].set_title('Q-Q Plot of Residuals')
    axes[1, 1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('regression_diagnostics.png', dpi=300, bbox_inches='tight')
    print("\\nRegression diagnostics saved as 'regression_diagnostics.png'")
    plt.show()
else:
    print("⚠ Install scikit-learn for regression analysis")
    print("  pip install scikit-learn")
`;
}

function generatePythonControlChart(): string {
  return `
# ============================================================
# CONTROL CHART ANALYSIS
# ============================================================

print("\\n" + "="*60)
print("CONTROL CHART ANALYSIS")
print("="*60)

def calculate_control_limits(data, chart_type='I-MR'):
    """Calculate control limits for control charts"""
    if chart_type == 'I-MR':
        # Individual chart
        x_bar = data.mean()
        mr = data.diff().abs().dropna()
        mr_bar = mr.mean()
        
        # Constants for n=2 (moving range)
        d2 = 1.128
        
        sigma = mr_bar / d2
        
        ucl = x_bar + 3 * sigma
        lcl = x_bar - 3 * sigma
        
        return x_bar, ucl, lcl, mr_bar
    
    return None, None, None, None

# Calculate limits
center_line, ucl, lcl, mr = calculate_control_limits(y)

print(f"\\nControl Chart Parameters (I-MR):")
print(f"  Center Line: {center_line:.4f}")
print(f"  UCL:         {ucl:.4f}")
print(f"  LCL:         {lcl:.4f}")
print(f"  MR-bar:      {mr:.4f}")

# Western Electric rules
def check_rules(data, ucl, lcl, center):
    """Check Western Electric control rules"""
    violations = []
    
    # Rule 1: Points beyond 3σ
    beyond = (data > ucl) | (data < lcl)
    if beyond.any():
        violations.append(f"Rule 1: {beyond.sum()} point(s) beyond limits")
    
    # Rule 2: 9 points on same side
    for i in range(len(data) - 8):
        segment = data.iloc[i:i+9]
        if (segment > center).all() or (segment < center).all():
            violations.append(f"Rule 2: 9 consecutive points on same side (starting at {i})")
            break
    
    # Rule 3: 6 points trending
    for i in range(len(data) - 5):
        segment = data.iloc[i:i+6]
        diffs = segment.diff().dropna()
        if (diffs > 0).all() or (diffs < 0).all():
            violations.append(f"Rule 3: 6 consecutive trending points (starting at {i})")
            break
    
    return violations

violations = check_rules(y, ucl, lcl, center_line)

print(f"\\nControl Chart Rules Check:")
if violations:
    for v in violations:
        print(f"  ⚠ {v}")
else:
    print("  ✓ No rule violations detected")

# Control limits for zones
zone_a_upper = center_line + 2 * (ucl - center_line) / 3
zone_a_lower = center_line - 2 * (center_line - lcl) / 3

# Plot control chart
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10))

# I-Chart
ax1.plot(y.index, y, 'bo-', markersize=4, label='Individual Values')
ax1.axhline(y=center_line, color='green', linestyle='-', linewidth=2, label=f'CL = {center_line:.3f}')
ax1.axhline(y=ucl, color='red', linestyle='--', linewidth=2, label=f'UCL = {ucl:.3f}')
ax1.axhline(y=lcl, color='red', linestyle='--', linewidth=2, label=f'LCL = {lcl:.3f}')
ax1.axhline(y=zone_a_upper, color='orange', linestyle=':', alpha=0.7, label='Zone A')
ax1.axhline(y=zone_a_lower, color='orange', linestyle=':', alpha=0.7)

# Highlight out-of-control points
out_of_control = (y > ucl) | (y < lcl)
if out_of_control.any():
    ax1.scatter(y[out_of_control].index, y[out_of_control], color='red', s=100, zorder=5, label='Out of Control')

ax1.set_xlabel('Sample')
ax1.set_ylabel('Value')
ax1.set_title('Individuals (I) Chart')
ax1.legend(loc='best')
ax1.grid(True, alpha=0.3)

# MR-Chart
mr_values = y.diff().abs().dropna()
mr_bar = mr_values.mean()
mr_ucl = 3.267 * mr_bar
mr_lcl = 0

ax2.plot(mr_values.index, mr_values, 'bs-', markersize=4, label='Moving Range')
ax2.axhline(y=mr_bar, color='green', linestyle='-', linewidth=2, label=f'MR-bar = {mr_bar:.3f}')
ax2.axhline(y=mr_ucl, color='red', linestyle='--', linewidth=2, label=f'UCL = {mr_ucl:.3f}')
ax2.axhline(y=mr_lcl, color='red', linestyle='--', linewidth=2, label='LCL = 0')

ax2.set_xlabel('Sample')
ax2.set_ylabel('Moving Range')
ax2.set_title('Moving Range (MR) Chart')
ax2.legend(loc='best')
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('control_chart.png', dpi=300, bbox_inches='tight')
print("\\nControl chart saved as 'control_chart.png'")
plt.show()
`;
}

function generatePythonANOVA(): string {
  return `
# ============================================================
# ANOVA (if categorical variables exist)
# ============================================================

print("\\n" + "="*60)
print("ANOVA ANALYSIS")
print("="*60)

# Check for categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

if len(categorical_cols) > 0 and STATSMODELS_AVAILABLE:
    cat_col = categorical_cols[0]
    num_col = numeric_cols[0]
    
    print(f"\\nOne-way ANOVA: {num_col} by {cat_col}")
    
    # Fit ANOVA model
    model = sm.formula.ols(f'{num_col} ~ C({cat_col})', data=df).fit()
    anova_table = sm.stats.anova_lm(model, typ=2)
    
    print("\\nANOVA Table:")
    print(anova_table)
    
    print(f"\\nModel Summary:")
    print(f"  R²: {model.rsquared:.4f}")
    print(f"  Adj R²: {model.rsquared_adj:.4f}")
    print(f"  F-statistic: {model.fvalue:.4f}")
    print(f"  Prob (F-statistic): {model.f_pvalue:.4e}")
    
    # Box plot by group
    plt.figure(figsize=(10, 6))
    df.boxplot(column=num_col, by=cat_col, ax=plt.gca())
    plt.title(f'{num_col} by {cat_col}')
    plt.suptitle('')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('anova_boxplot.png', dpi=300, bbox_inches='tight')
    print("\\nANOVA boxplot saved as 'anova_boxplot.png'")
    plt.show()
else:
    print("⚠ No categorical columns found for ANOVA")
`;
}

function generateJupyterNotebook(
  dataset: Dataset,
  results: AnalysisResults,
  _config: ExportConfig
): string {
  const cells = [
    {
      cell_type: 'markdown',
      metadata: {},
      source: `# Six Sigma Analysis Notebook\n\n**Project:** ${dataset.name}\n**Date:** ${new Date().toLocaleString()}\n\nThis notebook contains comprehensive Six Sigma analysis including:\n- Descriptive Statistics\n- Process Capability Analysis\n- Control Charts\n- Regression Analysis (if applicable)\n\n## Setup`,
    },
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      source: `# Import libraries\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\nfrom scipy.stats import norm, probplot\n\n# Configure plots\nsns.set_style(\"whitegrid\")\nplt.rcParams['figure.figsize'] = (12, 8)\n\nprint(\"✓ Libraries imported successfully\")`,
    },
    {
      cell_type: 'markdown',
      metadata: {},
      source: `## Load Data`,
    },
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      source: `# Create DataFrame\ndata_dict = {\n${dataset.columns.map((col, idx) => `    '${col.name}': [${dataset.rows.slice(0, 10).map(r => {
    const val = r[idx];
    if (val === null || val === undefined) return 'np.nan';
    if (typeof val === 'string') return `'${val}'`;
    return String(val);
  }).join(', ')}${dataset.rows.length > 10 ? ', ...' : ''}],`).join('\n')}\n}\n\ndf = pd.DataFrame(data_dict)\nprint(f\"Shape: {df.shape}\")\ndf.head()`,
    },
    {
      cell_type: 'markdown',
      metadata: {},
      source: `## Descriptive Statistics`,
    },
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      source: `# Calculate descriptive statistics\ndesc_stats = df.describe()\nprint(desc_stats)\n\n# Additional statistics\nnumeric_cols = df.select_dtypes(include=[np.number]).columns\nif len(numeric_cols) > 0:\n    y = df[numeric_cols[0]]\n    print(f\"\\nSkewness: {y.skew():.4f}\")\n    print(f\"Kurtosis: {y.kurtosis():.4f}\")`,
    },
  ];

  if (results.capability) {
    cells.push(
      {
        cell_type: 'markdown',
        metadata: {},
        source: `## Process Capability Analysis`,
      },
      {
        cell_type: 'code',
        execution_count: null,
        metadata: {},
        source: `# Capability analysis\nLSL = ${results.capability.lsl ?? 'None'}\nUSL = ${results.capability.usl ?? 'None'}\n\nmean = y.mean()\nstd = y.std()\n\nif USL and LSL:\n    cp = (USL - LSL) / (6 * std)\n    cpu = (USL - mean) / (3 * std)\n    cpl = (mean - LSL) / (3 * std)\n    cpk = min(cpu, cpl)\n    \n    print(f\"Cp: {cp:.3f}\")\n    print(f\"Cpk: {cpk:.3f}\")\n    print(f\"Sigma Level: {cpk * 3:.2f}\")`,
      }
    );
  }

  // Close the notebook
  cells.push({
    cell_type: 'markdown',
    metadata: {},
    source: `## Summary\n\nThis analysis was generated by the Six Sigma Training Platform.\n\n### Next Steps\n1. Review control charts for stability\n2. Investigate any out-of-control points\n3. Validate assumptions (normality, independence)\n4. Document findings and recommendations`,
  });

  const notebook = {
    cells,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.9.0',
      },
    },
    nbformat: 4,
    nbformat_minor: 4,
  };

  return JSON.stringify(notebook, null, 2);
}

function generateRequirements(): string {
  return `# Python Requirements for Six Sigma Analysis
# Generated by Six Sigma Training Platform
# Install with: pip install -r requirements.txt

# Core data analysis
numpy>=1.21.0
pandas>=1.3.0

# Statistical analysis
scipy>=1.7.0
statsmodels>=0.13.0

# Machine learning (optional, for regression)
scikit-learn>=1.0.0

# Visualization
matplotlib>=3.4.0
seaborn>=0.11.0

# Jupyter (optional, for notebooks)
jupyter>=1.0.0
ipython>=7.0.0

# Quality control specific
# Uncomment if available:
# quality-control>=0.1.0
`;
}

function generatePythonReadme(dataset: Dataset): string {
  return `# Six Sigma Python Analysis

**Dataset:** ${dataset.name}  
**Generated:** ${new Date().toLocaleString()}

## Files Included

- \`${dataset.name.replace(/\s+/g, '_')}_analysis.py\` - Main analysis script
- \`${dataset.name.replace(/\s+/g, '_')}_analysis.ipynb\` - Jupyter notebook version
- \`requirements.txt\` - Python dependencies
- \`README.md\` - This file

## Quick Start

### 1. Install Dependencies

\`\`\`bash
pip install -r requirements.txt
\`\`\`

### 2. Run Analysis

**Option A: Run Python Script**
\`\`\`bash
python ${dataset.name.replace(/\s+/g, '_')}_analysis.py
\`\`\`

**Option B: Use Jupyter Notebook**
\`\`\`bash
jupyter notebook ${dataset.name.replace(/\s+/g, '_')}_analysis.ipynb
\`\`\`

## Features

### Descriptive Statistics
- Mean, median, standard deviation
- Quartiles and IQR
- Skewness and kurtosis
- Missing value analysis

### Process Capability
- Cp, Cpk, Pp, Ppk indices
- Sigma level calculation
- DPMO estimation
- Normality testing

### Control Charts
- Individuals (I-MR) charts
- Western Electric rules
- Zone analysis
- Out-of-control detection

### Regression Analysis
- Linear regression
- R² and adjusted R²
- Residual diagnostics
- Prediction plots

### Visualizations
- Histogram with normal fit
- Box plots
- Q-Q plots
- Time series plots
- Control charts
- Capability plots

## Output Files

The script generates the following output files:
- \`six_sigma_analysis.png\` - Comprehensive analysis report
- \`control_chart.png\` - Control chart visualization
- \`regression_diagnostics.png\` - Regression diagnostic plots
- \`anova_boxplot.png\` - ANOVA visualization (if applicable)

## Customization

Edit the script to:
- Change column selections
- Modify specification limits
- Adjust chart parameters
- Add custom analyses

## References

- [NumPy Documentation](https://numpy.org/doc/)
- [Pandas Documentation](https://pandas.pydata.org/docs/)
- [SciPy Documentation](https://docs.scipy.org/)
- [Matplotlib Documentation](https://matplotlib.org/)
`;
}

/**
 * Generate Python class for reusable Six Sigma analysis
 */
export function generatePythonClass(): string {
  return `# Six Sigma Analysis Class
# Reusable Python class for Six Sigma statistical analysis

import numpy as np
import pandas as pd
from scipy import stats
from typing import Optional, Dict, Tuple, List

class SixSigmaAnalyzer:
    """
    Comprehensive Six Sigma analysis class.
    
    Provides methods for:
    - Descriptive statistics
    - Process capability analysis
    - Control chart calculations
    - Normality testing
    """
    
    def __init__(self, data: pd.Series):
        """
        Initialize analyzer with data.
        
        Args:
            data: pandas Series of measurements
        """
        self.data = data.dropna()
        self.n = len(self.data)
        self.mean = self.data.mean()
        self.std = self.data.std()
        
    def descriptive_stats(self) -> Dict:
        """Calculate comprehensive descriptive statistics."""
        return {
            'count': self.n,
            'mean': self.mean,
            'median': self.data.median(),
            'std': self.std,
            'min': self.data.min(),
            'max': self.data.max(),
            'q1': self.data.quantile(0.25),
            'q3': self.data.quantile(0.75),
            'skewness': self.data.skew(),
            'kurtosis': self.data.kurtosis(),
        }
    
    def capability(self, usl: float, lsl: float) -> Dict:
        """
        Calculate process capability indices.
        
        Args:
            usl: Upper specification limit
            lsl: Lower specification limit
            
        Returns:
            Dictionary with Cp, Cpk, and other metrics
        """
        cp = (usl - lsl) / (6 * self.std)
        cpu = (usl - self.mean) / (3 * self.std)
        cpl = (self.mean - lsl) / (3 * self.std)
        cpk = min(cpu, cpl)
        
        # Overall capability
        pp = (usl - lsl) / (6 * self.data.std(ddof=0))
        
        # Sigma level and DPMO
        sigma_level = cpk * 3
        dpmo = 2 * (1 - stats.norm.cdf(sigma_level)) * 1000000
        
        return {
            'cp': cp,
            'cpk': cpk,
            'cpu': cpu,
            'cpl': cpl,
            'pp': pp,
            'ppk': cpk,  # Simplified
            'sigma_level': sigma_level,
            'dpmo': dpmo,
        }
    
    def control_limits(self) -> Tuple[float, float, float]:
        """
        Calculate control limits for I-MR chart.
        
        Returns:
            Tuple of (center_line, ucl, lcl)
        """
        mr = self.data.diff().abs().dropna()
        mr_bar = mr.mean()
        
        # d2 constant for n=2
        d2 = 1.128
        sigma = mr_bar / d2
        
        ucl = self.mean + 3 * sigma
        lcl = self.mean - 3 * sigma
        
        return self.mean, ucl, lcl
    
    def normality_test(self) -> Dict:
        """Perform normality tests."""
        # Shapiro-Wilk test
        if self.n <= 5000:
            stat, p_value = stats.shapiro(self.data)
            test_name = 'Shapiro-Wilk'
        else:
            # Anderson-Darling for larger samples
            stat, critical, sig_levels = stats.anderson(self.data, dist='norm')
            p_value = None
            test_name = 'Anderson-Darling'
        
        return {
            'test': test_name,
            'statistic': stat,
            'p_value': p_value,
            'normal': p_value > 0.05 if p_value else None,
        }
    
    def check_control_rules(self) -> List[str]:
        """
        Check Western Electric control rules.
        
        Returns:
            List of rule violations
        """
        center, ucl, lcl = self.control_limits()
        violations = []
        
        # Rule 1: Points beyond 3σ
        beyond = (self.data > ucl) | (self.data < lcl)
        if beyond.any():
            violations.append(f"Rule 1: {beyond.sum()} point(s) beyond limits")
        
        # Rule 2: 9 points on same side
        for i in range(len(self.data) - 8):
            segment = self.data.iloc[i:i+9]
            if (segment > center).all() or (segment < center).all():
                violations.append(f"Rule 2: 9 consecutive points on same side")
                break
        
        return violations

# Example usage
if __name__ == "__main__":
    # Create sample data
    data = pd.Series(np.random.normal(50, 5, 100))
    
    # Initialize analyzer
    analyzer = SixSigmaAnalyzer(data)
    
    # Get statistics
    print("Descriptive Statistics:")
    print(analyzer.descriptive_stats())
    
    # Capability analysis
    print("\\nCapability Analysis:")
    print(analyzer.capability(usl=60, lsl=40))
    
    # Control limits
    print("\\nControl Limits:")
    print(analyzer.control_limits())
    
    # Normality test
    print("\\nNormality Test:")
    print(analyzer.normality_test())
    
    # Control rules
    print("\\nControl Rule Violations:")
    violations = analyzer.check_control_rules()
    print(violations if violations else "No violations")
`;
}
