/**
 * SPSS Export Generator
 * 
 * Generates SPSS syntax and data files for Six Sigma analysis
 */

import type { Dataset, AnalysisResults, ExportConfig } from '../types';

export interface SPSSExport {
  syntax: string;
  dataFile: string;
  outputTemplate: string;
  filename: string;
}

/**
 * Generate SPSS syntax for complete analysis
 */
export function generateSPSSExport(
  dataset: Dataset,
  results: AnalysisResults,
  config: ExportConfig
): SPSSExport {
  const syntax = generateSPSSSyntax(dataset, results, config);
  const dataFile = generateSPSSDataFile(dataset);
  const outputTemplate = generateSPSSOutputTemplate(dataset, results);
  
  return {
    syntax,
    dataFile,
    outputTemplate,
    filename: `${dataset.name.replace(/\s+/g, '_')}_SPSS.sps`,
  };
}

function generateSPSSSyntax(
  dataset: Dataset,
  results: AnalysisResults,
  _config: ExportConfig
): string {
  return `* Six Sigma Analysis - SPSS Syntax
* Generated by Six Sigma Training Platform
* Date: ${new Date().toLocaleString()}
* Dataset: ${dataset.name}

* ============================================================
* DATA DEFINITION
* ============================================================

DATA LIST FREE
${dataset.columns.map((col) => `  /${col.name.substring(0, 8).toUpperCase().replace(/\s/g, '_')} ${getSPSSFormat(col.type)}`).join('\n')}.
BEGIN DATA.
${dataset.rows.slice(0, 100).map(row => 
  '  ' + row.map(cell => {
    if (cell === null || cell === undefined) return '';
    if (typeof cell === 'string') return `"${cell.substring(0, 32)}"`;
    return String(cell);
  }).join(' ')
).join('\n')}
${dataset.rows.length > 100 ? '* ... (truncated for display)' : ''}
END DATA.

* ============================================================
* VARIABLE LABELS
* ============================================================

VARIABLE LABELS
${dataset.columns.map((col) => `  ${col.name.substring(0, 8).toUpperCase().replace(/\s/g, '_')} "${col.name}${col.description ? ` - ${col.description}` : ''}"`).join('\n')}.

* ============================================================
* VALUE LABELS (if categorical)
* ============================================================

* VALUE LABELS GROUP 1 'Group A' 2 'Group B'.

* ============================================================
* DESCRIPTIVE STATISTICS
* ============================================================

TITLE 'Descriptive Statistics'.
DESCRIPTIVES VARIABLES=${dataset.columns.filter(c => c.type === 'numeric').map(c => c.name.substring(0, 8).toUpperCase().replace(/\s/g, '_')).join(' ')} 
  /STATISTICS=MEAN STDDEV VARIANCE MIN MAX SEMEAN KURTOSIS SKEWNESS.

* Detailed statistics with percentiles
FREQUENCIES VARIABLES=${dataset.columns.filter(c => c.type === 'numeric').map(c => c.name.substring(0, 8).toUpperCase().replace(/\s/g, '_')).slice(0, 5).join(' ')} 
  /FORMAT=NOTABLE 
  /STATISTICS=STDDEV VARIANCE RANGE MINIMUM MAXIMUM SEMEAN 
    MEAN MEDIAN MODE SUM SKEWNESS SESKEW KURTOSIS SEKURT 
    PERCENTILES(25, 50, 75) 
  /ORDER=ANALYSIS.

* ============================================================
* GRAPHS - DESCRIPTIVE
* ============================================================

* Histogram with normal curve
GRAPH /HISTOGRAM(NORMAL)=${dataset.columns.find(c => c.type === 'numeric')?.name.substring(0, 8).toUpperCase().replace(/\s/g, '_') || 'VAR1'}.

* Boxplot
EXAMINE VARIABLES=${dataset.columns.find(c => c.type === 'numeric')?.name.substring(0, 8).toUpperCase().replace(/\s/g, '_') || 'VAR1'} 
  /PLOT BOXPLOT STEMLEAF 
  /COMPARE GROUP 
  /STATISTICS DESCRIPTIVES 
  /CINTERVAL 95 
  /MISSING LISTWISE 
  /NOTOTAL.

* Q-Q plot for normality
PPLOT /VARIABLES=${dataset.columns.find(c => c.type === 'numeric')?.name.substring(0, 8).toUpperCase().replace(/\s/g, '_') || 'VAR1'} 
  /NOLOG 
  /NOSTANDARDIZE 
  /TYPE=Q-Q 
  /FRACTION=BLOM 
  /TIES=MEAN 
  /DIST=NORMAL.

${results.capability ? generateSPSSCapabilityAnalysis() : ''}

${results.controlChart ? generateSPSSControlChart() : ''}

${results.regression ? generateSPSSRegression() : ''}

${results.anova ? generateSPSSANOVA() : ''}

* ============================================================
* ADDITIONAL SIX SIGMA ANALYSES
* ============================================================

* Normality tests
NPAR TESTS /K-S(NORMAL)=${dataset.columns.find(c => c.type === 'numeric')?.name.substring(0, 8).toUpperCase().replace(/\s/g, '_') || 'VAR1'} 
  /MISSING ANALYSIS.

* Shapiro-Wilk test (if available)
* EXAMINE VARIABLES=VAR1 
  /STATISTICS NONE 
  /PLOT NPPLOT 
  /MISSING LISTWISE.

* ============================================================
* OUTPUT EXPORT
* ============================================================

* Export results to Excel
OUTPUT EXPORT 
  /XLSX DOCUMENTFILE='${dataset.name.replace(/\s+/g, '_')}_results.xlsx' 
  /OPERATION=CREATEFILE.

* Export charts
OUTPUT EXPORT 
  /PNG DOCUMENTFILE='${dataset.name.replace(/\s+/g, '_')}_charts.png' 
  /OPERATION=CREATEFILE.

* ============================================================
* SAVE DATA
* ============================================================

SAVE OUTFILE='${dataset.name.replace(/\s+/g, '_')}.sav' 
  /COMPRESSED.

EXECUTE.
`;
}

function getSPSSFormat(type: string): string {
  switch (type) {
    case 'numeric':
      return 'F8.4';
    case 'date':
      return 'ADATE10';
    case 'categorical':
    case 'text':
    default:
      return 'A32';
  }
}

function generateSPSSCapabilityAnalysis(): string {
  return `
* ============================================================
* PROCESS CAPABILITY ANALYSIS
* ============================================================

TITLE 'Process Capability Analysis'.

* Note: SPSS requires the Quality Control or Process Capability module
* Below is the syntax structure - modify limits as needed

* Set specification limits
* USL = Upper Specification Limit
* LSL = Lower Specification Limit
* TARGET = Target value

* Calculate basic statistics for capability
DESCRIPTIVES VARIABLES=VAR1 
  /STATISTICS=MEAN STDDEV MIN MAX.

* Calculate Cp and Cpk manually using COMPUTE
* (Replace VAR1 with your variable name)
* COMPUTE MEAN_VAL = MEAN(VAR1).
* COMPUTE STD_VAL = SD(VAR1).
* COMPUTE USL = 100.  /* Enter your USL */
* COMPUTE LSL = 0.    /* Enter your LSL */
* COMPUTE CP = (USL - LSL) / (6 * STD_VAL).
* COMPUTE CPU = (USL - MEAN_VAL) / (3 * STD_VAL).
* COMPUTE CPL = (MEAN_VAL - LSL) / (3 * STD_VAL).
* COMPUTE CPK = MIN(CPU, CPL).
* EXECUTE.

* Display capability indices
* DESCRIPTIVES VARIABLES=CP CPK CPU CPL 
  /STATISTICS=MEAN.

* Histogram with specification limits
GRAPH 
  /HISTOGRAM=VAR1 
  /TITLE='Process Capability'.

* Add reference lines (manual annotation required in output)
`;
}

function generateSPSSControlChart(): string {
  return `
* ============================================================
* CONTROL CHARTS
* ============================================================

TITLE 'Control Chart Analysis'.

* Individuals (I) and Moving Range (MR) Chart
* Requires Quality Control module

* For individual observations
GRAPH 
  /LINE(MULTIPLE)=MEAN(VAR1) BY $CASENUM 
  /TITLE='Individuals Chart'.

* X-bar and R chart (if subgroup data available)
* XGRAPH CHART=MEAN(Measure) BY Subgroup /TYPE=LINE.

* Note: Full SPC charts require:
* 1. Quality Control module, or
* 2. Manual calculation of control limits

* Calculate moving range
* CREATE MR = DIFF(VAR1).
* COMPUTE MR = ABS(MR).
* EXECUTE.

* Calculate control limits manually
* COMPUTE MR_BAR = MEAN(MR).
* COMPUTE X_BAR = MEAN(VAR1).
* COMPUTE E2 = 2.660.  /* Constant for n=2 */
* COMPUTE UCL = X_BAR + E2 * MR_BAR.
* COMPUTE LCL = X_BAR - E2 * MR_BAR.
* EXECUTE.

* Plot with control limits
GRAPH 
  /SCATTERPLOT(BIVAR)=$CASENUM WITH VAR1 
  /TITLE='Control Chart'.
`;
}

function generateSPSSRegression(): string {
  return `
* ============================================================
* REGRESSION ANALYSIS
* ============================================================

TITLE 'Regression Analysis'.

* Simple linear regression (modify variables as needed)
REGRESSION 
  /DESCRIPTIVES MEAN STDDEV CORR SIG N 
  /MISSING LISTWISE 
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL 
  /CRITERIA=PIN(.05) POUT(.10) 
  /NOORIGIN 
  /DEPENDENT VAR2    /* Response variable */
  /METHOD=ENTER VAR1 /* Predictor variable */
  /SCATTERPLOT=(*ZRESID , *ZPRED) 
  /RESIDUALS HISTOGRAM(ZRESID) NORMPROB(ZRESID).

* Save predicted values and residuals
* REGRESSION 
  /SAVE PRED RESID.

* Residual analysis
EXAMINE VARIABLES=RES_1 
  /PLOT BOXPLOT STEMLEAF NPPLOT 
  /COMPARE GROUP 
  /STATISTICS DESCRIPTIVES 
  /CINTERVAL 95 
  /MISSING LISTWISE 
  /NOTOTAL.

* Durbin-Watson test for autocorrelation
REGRESSION 
  /DESCRIPTIVES MEAN STDDEV CORR SIG N 
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE SELECTION 
  /DEPENDENT VAR2 
  /METHOD=ENTER VAR1 
  /RESIDUALS DURBIN.
`;
}

function generateSPSSANOVA(): string {
  return `
* ============================================================
* ANOVA
* ============================================================

TITLE 'ANOVA Analysis'.

* One-way ANOVA (modify variables as needed)
ONEWAY VAR1 BY GROUP 
  /STATISTICS DESCRIPTIVES HOMOGENEITY 
  /PLOT MEANS 
  /MISSING ANALYSIS 
  /POSTHOC=TUKEY ALPHA(0.05).

* General Linear Model (if multiple factors)
UNIANOVA VAR1 BY FACTOR1 FACTOR2 
  /METHOD=SSTYPE(3) 
  /INTERCEPT=INCLUDE 
  /POSTHOC=FACTOR1 FACTOR2(TUKEY) 
  /PLOT=PROFILE(FACTOR1*FACTOR2) 
  /EMMEANS=TABLES(FACTOR1) 
  /EMMEANS=TABLES(FACTOR2) 
  /EMMEANS=TABLES(FACTOR1*FACTOR2) 
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY 
  /CRITERIA=ALPHA(.05) 
  /DESIGN=FACTOR1 FACTOR2 FACTOR1*FACTOR2.

* Non-parametric alternative (Kruskal-Wallis)
NPAR TESTS 
  /K-W=VAR1 BY GROUP(1 3) 
  /MISSING ANALYSIS.
`;
}

function generateSPSSDataFile(dataset: Dataset): string {
  return `* SPSS Data File - ${dataset.name}
* Import this data into SPSS using:
* File > Open > Data
* Select file type: Text (CSV, TSV, TXT)
* Follow import wizard

* Column Definitions:
${dataset.columns.map((col, idx) => `*   ${idx + 1}. ${col.name} (${col.type})`).join('\n')}

* Data values below (CSV format):
${dataset.columns.map(col => col.name).join(',')}
${dataset.rows.slice(0, 200).map(row => 
  row.map(cell => {
    if (cell === null || cell === undefined) return '';
    if (typeof cell === 'string') return `"${cell}"`;
    return String(cell);
  }).join(',')
).join('\n')}
${dataset.rows.length > 200 ? `
* ... (${dataset.rows.length - 200} more rows)` : ''}
`;
}

function generateSPSSOutputTemplate(dataset: Dataset, results: AnalysisResults): string {
  return `Six Sigma Analysis Output Template
===================================

Dataset: ${dataset.name}
Date: ${new Date().toLocaleString()}

DESCRIPTIVE STATISTICS
----------------------
${dataset.columns.filter(c => c.type === 'numeric').map(col => `
Variable: ${col.name}
  Mean: 
  Std Dev: 
  Min: 
  Max: 
  Median: 
  Q1: 
  Q3: 
`).join('')}

${results.capability ? `CAPABILITY ANALYSIS
-------------------
USL: 
LSL: 
Target: 

Indices:
  Cp: 
  Cpk: 
  Cpu: 
  Cpl: 
  Pp: 
  Ppk: 

Sigma Level: 
DPMO: 
Yield: %

Interpretation:
[ ] Cpk >= 1.33 (Capable)
[ ] 1.0 <= Cpk < 1.33 (Marginal)
[ ] Cpk < 1.0 (Not Capable)
` : ''}

${results.controlChart ? `CONTROL CHART ANALYSIS
----------------------
Chart Type: I-MR

Control Limits:
  Center Line: 
  UCL: 
  LCL: 

Violations:
[ ] Rule 1: Points beyond limits
[ ] Rule 2: 9 points same side
[ ] Rule 3: 6 points trending
[ ] Rule 4: 14 points alternating
[ ] Rule 5: 2 of 3 in Zone A
[ ] Rule 6: 4 of 5 in Zone B
[ ] Rule 7: 15 points in Zone C
[ ] Rule 8: 8 points beyond Zone C

Process Status: [ ] Stable [ ] Unstable
` : ''}

${results.regression ? `REGRESSION ANALYSIS
-------------------
Dependent Variable: 
R²: 
Adjusted R²: 
Standard Error: 

Coefficients:
  Intercept: 
  Slope: 

ANOVA:
  F-statistic: 
  p-value: 

Assumptions:
[ ] Linearity
[ ] Independence
[ ] Normality of residuals
[ ] Equal variance
` : ''}

CONCLUSIONS & RECOMMENDATIONS
-----------------------------
1. 
2. 
3. 

Next Steps:
[ ] Validate measurement system
[ ] Investigate special causes
[ ] Implement control plan
[ ] Monitor process

Analyst: _________________
Date: _________________
`;
}

/**
 * Generate SPSS command reference
 */
export function generateSPSSCommandReference(): string {
  return `# SPSS Command Reference for Six Sigma

## File Operations

| Command | Description |
|---------|-------------|
| GET FILE | Open SPSS data file |
| SAVE OUTFILE | Save data file |
| IMPORT | Import external data |
| EXPORT | Export data |

## Data Definition

| Command | Description |
|---------|-------------|
| DATA LIST | Define variable structure |
| VARIABLE LABELS | Add variable descriptions |
| VALUE LABELS | Define value labels |
| MISSING VALUES | Define missing values |
| COMPUTE | Create new variables |
| RECODE | Recode values |

## Descriptive Statistics

| Command | Description |
|---------|-------------|
| DESCRIPTIVES | Basic statistics |
| FREQUENCIES | Frequency tables |
| MEANS | Group means |
| EXAMINE | Explore data |
| CROSSTABS | Cross-tabulation |

## Statistical Tests

| Command | Description |
|---------|-------------|
| T-TEST | T-tests |
| ONEWAY | One-way ANOVA |
| UNIANOVA | General linear model |
| GLM | Repeated measures ANOVA |
| NPAR TESTS | Non-parametric tests |
| CORRELATIONS | Correlation matrix |
| REGRESSION | Linear regression |

## Quality Control

| Command | Description |
|---------|-------------|
| SPCHART | Control charts |
| CAPABILITY | Process capability |
| PARETO | Pareto chart |
| QC | Quality control procedures |

## Graphs

| Command | Description |
|---------|-------------|
| GRAPH | Create charts |
| GGRAPH | General graphics |
| IGRAPH | Interactive graphs |
| PPLOT | Probability plots |

## Output

| Command | Description |
|---------|-------------|
| OUTPUT EXPORT | Export output |
| OUTPUT SAVE | Save output |
| TITLE | Add title |
| SUBTITLE | Add subtitle |

## Example Workflow

\`\`\`
* Load data
GET FILE='data.sav'.

* Descriptive statistics
DESCRIPTIVES ALL.

* Normality test
EXAMINE VARIABLES=Measure /PLOT NPPLOT.

* Capability (if module available)
* CAPABILITY Measure /USL=100 /LSL=0.

* Control chart
* SPCHART /TYPE=IR Measure.

* Save output
OUTPUT SAVE OUTFILE='results.spv'.
\`\`\`
`;
}
